### ISSUE TITLE
PET json information

### ISSUE THREAD

**Issue by MarDos1234** [rordenlab/dcm2niix#802] opened 2024-03-07 08:04 UTC
Dear dcm2niix users,

is it possible to modify which tag will be in json file?

For calculation of SUVlbm in PET imaging it is necessary to know patients height, but it is not in json file and in DICOM it is. Is it possible to add which tag should be displayed in json?

Thank you,

Best regrads,

Marek

**Comment by neurolabusc** [comment] 2024-03-07 12:00
The patient weight is considered [private health information](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#global-private-information) and will only be included if you disable BIDS anonymization (`-ba`):

```
dcm2niix -ba n /path/to/DICOMs
```

**Comment by MarDos1234** [comment] 2024-03-07 12:19
Thank you, but I need height not weight (I know about -ba).

**Comment by bendhouseart** [comment] 2024-03-07 14:05
Yeah, easy enough to switch our call of dcm2niix to use `-ba n` with an additional flag. Conversely, PET2BIDS already extracts extra values from the dicom headers that dcm2niix does not if you want to place this entirely on us @neurolabusc.

**Comment by MarDos1234** [comment] 2024-03-08 05:20
I tried dcm2niix4pet but json does not contains neither weight nor height :(

**Comment by CPernet** [comment] 2024-03-08 06:56
Hi Marek, we know that. Here we are just checking with Chris to how we will do it. Since such info is rather PET centric (although generally weight/BMI is of interest to adjust for dose), i propose that we add an argument to dcm2niix4pet and we'll just handle the dicom tags. 

@MarDos1234 I tagged you into a new issue on our repository.

**Comment by neurolabusc** [comment] 2024-03-11 12:26
I have made a commit to the development branch (v1.0.20240308) that adds [PatientsSize to the Global Private Information](https://github.com/rordenlab/dcm2niix/tree/development/BIDS#global-private-information) (so requires `ba n`). I have also made some changes to the [PET fields](https://github.com/rordenlab/dcm2niix/tree/development/BIDS#modality-positron-emission-tomography). Unfortunately, the BIDS PET specification adopted some different names than DICOM and prior dcm2niix releases. I have adopted the newly minted BIDS names, but this will be a breaking change for users assuming the old naming scheme. The [dcm2niix PET BIDS notes](https://github.com/rordenlab/dcm2niix/tree/development/BIDS#modality-positron-emission-tomography) also mention some challenges in converting a few DICOM tags to the BIDS ones. I would be happy to work with the PET2BIDS team to see if we can add the logic to better resolve these tags. It should be noted that in most cases the PET DICOMs do not contain sufficient details for full analysis, and therefore dcm2niix will always depend on wrapper like PET2BIDS to create reproducible datasets.Its great to have that team acquiring validation datasets across manufacturers and software versions to provide a relatively painless solution.

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

**Comment by CPernet** [comment] 2024-03-11 13:21
so funny ... 

> we can add the logic 

is translated by myself as 

> we can build heuristics since manufacturer names have no logic

we use this [json file](https://github.com/openneuropet/PET2BIDS/blob/main/metadata/PET_reconstruction_methods.json) to map silly names to actual to human understandable names

**Comment by neurolabusc** [comment] 2024-03-11 20:09
@CPernet 

1. I have added code that attempts to include your naming.
2. Below is a simple JSON to C parser, so as you update your naming JSON we could add this directly into dcm2niix.
```
import json

def generate_c_name(json_data):
    c_code = ""
    for method in json_data["reconstruction_method"]:
        contents = method["contents"]
        recon_method_name = method["ReconMethodName"]
        
        c_code += f'if (strstr(d.reconstructionMethod, "{contents}"))\n'
        c_code += f'    strcpy(reconMethodName, "{recon_method_name}");\n'
        c_code += 'else '
    # Remove the trailing "else"
    c_code = c_code[:-5]
    return c_code

# Read JSON file
with open('PET_reconstruction_methods.json') as json_file:
    json_data = json.load(json_file)

# Generate C names
c_code = generate_c_name(json_data)
# Print or save the generated C code
print(c_code)
```

**Comment by neurolabusc** [comment] 2024-03-29 12:42
Closing, development branch adopts tags identified by @CPernet and replaces the original BIDS field names with those chosen by the PET BIDS BEP team.

**Closed** 2024-03-29 12:43 UTC

**Comment by bendhouseart** [comment] 2024-04-02 15:38
Missed this while on leave; thanks @neurolabusc you're my hero!
