### ISSUE TITLE
Prostate - Philips Ingenia DWI bvals incorrect

### ISSUE THREAD

**Issue by dagra** [rordenlab/dcm2niix#405] opened 2020-07-03 14:44 UTC
Hi,

I tried to convert a prostate DWI series from Philips Ingenia with the latest release and the produced bvals are all `0`, but the correct values are `0, 500, 1500`. The output is the following:

```
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 87 DICOM file(s)
Image Decompression is new: please validate conversions
Warning: No bvec/bval files created: only single value after ADC excluded
Using RWVSlope:RWVIntercept = 1.69988:0
 Philips Scaling Values RS:RI:SS = 1.69988:0:0.0416744 (see PMC3998685)
Convert 87 DICOM as ./__DWI_3b_ZOOM_0-500-1500_20200612142332_901 (112x112x29x3)
Conversion required 0.097204 seconds (0.094655 for core code).
```

The corresponding tags that encode this information are correct as far as I can tell:

```
(0018,9087) FD 0                                        #   8, 1 DiffusionBValue
(0018,9089) FD 0\0\0                                    #  24, 3 DiffusionGradientOrientation
```

```
(0018,9087) FD 500                                      #   8, 1 DiffusionBValue
(0018,9089) FD 0\0\0                                    #  24, 3 DiffusionGradientOrientation
```

```
(0018,9087) FD 1500                                     #   8, 1 DiffusionBValue
(0018,9089) FD 0\0\0                                    #  24, 3 DiffusionGradientOrientation
```

Judging from [your comment in issue 402](https://github.com/rordenlab/dcm2niix/issues/402#issuecomment-638961690) and the description in [namic-wiki](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_Philips), these images are typically derived (e.g. TRACE), but this is not the case here. They are raw images with zero gradient and non-zero b-value.

Since this is a prostate series, I understand that it may be out of scope of dcm2niix, but it seems to me that this could be a valid brain DWI also, although not typical. I would be grateful for any help. If it's necessary, I can send you privately the series.

Thanks

**Comment by neurolabusc** [comment] 2020-07-03 16:27
The DICOM header clearly describes these as having no vector direction/length (e.g. the vector in 0018,9089 has a length of 0). This is typical of derived images and images like TRACE/ADC/MD which do not have a diffusion vector. If these are indeed raw diffusion-weighted DTI-suitable images, the bvec information has been lost. Since this information is not present in the DICOM header, it is impossible for dcm2niix to infer the applied vector. Therefore, this is an issue with your image data, not dcm2niix. dcm2niix assumes that your [DICOM images are truthful](https://en.wikipedia.org/wiki/Quis_custodiet_ipsos_custodes%3F), it can not resolve situations where the information in the DICOM header is not accurate (though it often warns users of implausible values). 

If you are at a center with a Philips research agreement, I would contact your Philips research collaboration manager for support and a possible bug report. Failing that, @drmclem often has insight into Philips data.

**Comment by drmclem** [comment] 2020-07-03 17:10
Hi

I thought I had commented on this before but can't find it. This is a clincial  isotropic diffusion weighted acqusition (DWI). Its a single scan where the diffusion is applied in multiple directions during the acquistion and the final image is trace weighted, so not post processed and the invidual directions are not available. We have both DWI and DTI variants available to the user.

So this is the intended behaviour.

Matthew

**Comment by neurolabusc** [comment] 2020-07-03 18:22
Thanks @drmclem that explains it. The output reported just three volumes (112x112x29x**3**), so it is clearly not a raw research DTI scan (fitting a tensor requires at least 6 indpendent vectors, though [more are recommended](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy#If_you_haven.27t_already_acquired_your_data)). So the user has a B0 image and a TRACE image for each b-value.

**Comment by dagra** [comment] 2020-07-03 18:46
@neurolabusc 

> If these are indeed raw diffusion-weighted DTI-suitable images, the bvec information has been lost. Since this information is not present in the DICOM header, it is impossible for dcm2niix to infer the applied vector.

These are not DTI-suitable images. It's [simple DWI](https://en.wikipedia.org/wiki/Diffusion_MRI#Applications_of_DWI) and it's used for example to compute the ADC. So, I'm not expecting from dcm2niix to infer the vectors, but I would expect to produce the associated b-values, i.e. `0 500 1500`. In other vendors, dcm2niix successfully produces the correct bvals and bvecs. For example, in the [public dataset of the prostatex](https://wiki.cancerimagingarchive.net/display/Public/SPIE-AAPM-NCI+PROSTATEx+Challenges) the output of dcm2niix for the first subject in the DWI is: b-values: `50 400 800`,
b-vectors:
```
0 0 0
0 0 0
0 0 0
```

So, I'd expect something similar in my case.

> So this is the intended behaviour.

@drmclem do you refer to the dcm2niix  and that the expected output for the b-values should be all `0`? Or do you refer to the information that is encoded in my dicoms and that they are correct?

> So the user has a B0 image and a TRACE image for each b-value.

So, the 2nd and 3rd volumes are not raw, but TRACE? Because TRACE is not mentioned anywhere in the tags (e.g. the tag `(0008,0008)` is `[ORIGINAL\PRIMARY\M_SE\M\SE]` in all frames. But If they are indeed TRACE, I have misunderstood it and probably misled you, I'm sorry.

**Comment by neurolabusc** [comment] 2020-07-03 19:47
@dagra, feel free to send samples via DropBox or Google Drive to the email listed in my avatar. I do not have Philips equipment, and my tools are typically used for research sequences where the raw diffusion images with b-vectors are recorded. This allows users to generate there own ADC/MD/TRACE/etc derived images after offline processing (e.g. my pipeline uses DeGibbs, DeNoise, Eddy, TOPUP). If a research sequence is designed to be compatible with these tools, one can calculate the desired derived measures after processing. In particular, the ability to correct spatial distortions is important for research studies, where we want to make comparisons between individuals. Clinical scans tend to be designed for rapid acquisition and a human making a judgment for that specific individual. While these are important, I have much less experience with this domain. Further, if a clinical image does not provide rich meta data, it is hard to know how to describe the resulting image in NIfTI: is it TRACE, ADC, MD, FA, MK, etc?

The intended behavior is for dcm2niix to create a collection of the B=0 images and the DIRECTIONAL B>0 images. By design, dcm2niix will purge ISOTROPIC images with B>0 if they exist in a series that includes DIRECTIONAL images. The reason for this is that the ISOPTROPIC images will disrupt the subsequent processing, and better ISOTROPIC images can be derived after processing. Therefore, dcm2niix only preserved your ISOTROPIC images because they were in a series which did not include DIRECTIONAL images. Tools like dtifit expect both a bvec and bval. While I guess we could create a bval file in isolation, I simply have no experience with these images, and without knowing the measure I think they may be underspecified for further analyses.

You make an interesting point that for the TCIA images you link dcm2niix does generate bval and zeroed bvec files. I suspect this reflects that they came from a Siemens scanner that uses a different DICOM tags for encoding gradients (and does list these as being DERIVED TRACE images). I suspect the reason I have not noted this before is that I run dcm2niix to ignore derived images (`-i y`), again because I can generate better derived measures after processing. Regardless, these isotropic images fall outside the remit of the FSL bvec/bval format as well as the BIDS specification. It is really unclear what the correct solution is.

**Comment by neurolabusc** [comment] 2020-07-04 11:25
You can build the latest commit of the development branch (v1.0.20200704). It will generate bval files for series where all the images are isotropic. This mimic the behavior of the Siemens dataset you linked ([see issue 352](https://github.com/rordenlab/dcm2niix/issues/352)). Now the behavior is consistent across vendors. I still feel a bit squeamish about this solution, as when users see bvec/bval files they will assume these are directional scans. Isotropic series are really outside the remit of FSL and BIDS, so the correct behavior is not specified. I have tried to generate meaningful warnings for these images. Hopefully, most research scientists who expect FSL/BIDS data will never acquire isotropic data.

As an aside, I would check the provenance of these images. Several of the DICOM tags seem to have been replaced by bogus values. I suspect these values were corrupted by a PACS transfer or a poorly implemented anonymization. The pattern of corruption appears [identical to issue 402](https://github.com/rordenlab/dcm2niix/issues/402). The tool that corrupted these tags should be identified and patched. In this instance, dcm2niix does not require any of the corrupted tags, but this will have unintended consequences for any tool that relies on these tags:
```

    (0018,9019) FD 7.229999999999997e+75                    #   8, 1 TagAngleFirstAxis
    (0018,9030) FD 7.229999999999997e+75                    #   8, 1 TagSpacingFirstDimension
    (0018,9602) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXX
    (0018,9603) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXY
    (0018,9604) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXZ
    (0018,9605) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueYY
    (0018,9606) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueYZ
    (0018,9607) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueZZ
    (0020,9256) FD 7.229999999999997e+75                    #   8, 1 RespiratoryTriggerDelayThreshold

```

The ImplementationVersionName (0002,0013) reports `OFFIS_DCMTK_365`. In my experience, DCMTK is extremely reliable, and I doubt it is the source of this corruption. I note that PatientName (0010,0010) shows an unusual pattern of anonymization (`ANON_182dca37-4ea...`) so my guess is that the anonymization tool may be the culprit for corrupting these tags.

**Comment by dagra** [comment] 2020-07-06 17:46
I tested the series with the development branch and it produces the bval file successfully. Thanks!

Since I was on it and in order to have a more complete image regarding this kind of series, I tried to find more series from various vendors and models. So, I found 2 (out of 13) more cases where the bval files were incorrect (or missing). I will check if I can share them with you.

**Comment by drmclem** [comment] 2020-07-07 10:21
Hi - Some addtional comments

My reading of the http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.13.5.9.html is that the Bmatrix tags ((0018,9602) etc) are only required to be valid if the diffusion directionality is BMATRIX ((0018,9075).

I've had a look at some DWI v DTI philips data - the bmatrix tags have been added after export from the scanner and are not present at source but the images are correctly labeled  depending on their origin.

        (0018,9075) CS [DIRECTIONAL]                            #  12, 1 DiffusionDirectionality
        (0018,9075) CS [DIRECTIONAL]                            #  12, 1 DiffusionDirectionality
        (0018,9075) CS [ISOTROPIC]                              #  10, 1 DiffusionDirectionality
        (0018,9075) CS [NONE]                                   #   4, 1 DiffusionDirectionality

**Comment by neurolabusc** [comment] 2020-07-07 10:37
Thanks @drmclem for the details. @dagra you it might be worth identifying which tool added this odd tags. Since dcm2niix does not use these tags and the development release fulfills your request, I am closing this issue. The fact that dcm2niix will create .bval files for isotropic images may require some pipelines that use dcm2niix to be modified. I will not that in the release notes for the next stable version.

**Closed by neurolabusc** 2020-07-07 10:37 UTC
