### ISSUE TITLE
BIDS sidecar field ParallelReductionFactorInPlane too large

### ISSUE THREAD

**Issue by lukeje** [rordenlab/dcm2niix#672] opened 2023-01-26 20:40 UTC
**Describe the bug**

The reported ParallelReductionFactorInPlane in the JSON sidecar file for Siemens data is the product of the [in-plane](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.metadata.ParallelReductionFactorInPlane) and [out-of-plane](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.metadata.ParallelReductionFactorOutOfPlane) parallel reduction factors.

I think the problem occurs because `accelFactPE` (which is the source of ParallelReductionFactorInPlane for Siemens data) is [read from a string](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/nii_dicom.cpp#L5888) which contains the total acceleration, not just the in-plane acceleration.

**To reproduce**

1. Download the `B1+_mapping` DICOM dataset from [here](https://owncloud.gwdg.de/index.php/s/iv2TOQwGy4FGDDZ), measured on a Siemens scanner with GRAPPA 2×2 (i.e. it should give `ParallelReductionFactorInPlane = 2`, `ParallelReductionFactorOutOfPlane = 2`)
2. Run dcm2niix on the DICOM files
3. See that the ParallelReductionFactorInPlane is 4 in the BIDS sidecar files, rather than 2.

**Expected behavior**

Ideally both ParallelReductionFactorInPlane and ParallelReductionFactorOutOfPlane would be 2, rather than ParallelReductionFactorInPlane being the product of the two in the JSON sidecar files. Note that `AccelFact3D` in the BIDS sidecar is 2, as expected.

Note that this data does come from a "user" sequence, but based on [this comment](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/nii_dicom_batch.cpp#L1765) in the dcm2niix source code, this is not the only dataset where this is a problem.

**Version**

Tested with the current master branch:
- Chris Rorden's dcm2niiX version v1.0.20220720  GCC9.4.0 x86-64 (64-bit Linux)

Tested with the latest development branch:
- Chris Rorden's dcm2niiX version v1.0.20230121  GCC9.4.0 x86-64 (64-bit Linux)

**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)?
 
It is the latest stable release.

 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue?

No, the development branch did not resolve the issue.

**Comment by neurolabusc** [comment] 2023-01-26 21:21
@lukeje can you communicate with your Siemens Research Collaboration manager to help out with this. The DICOM header is not internally consistent.

While the CSA header suggests `ParallelReductionFactorInPlane = 2` and `ParallelReductionFactorOutOfPlane = 2`:
```
sPat.lAccelFactPE	 = 	2
sPat.lAccelFact3D	 = 	2
```

The private tag suggests  `ParallelReductionFactorInPlane = 4` and `ParallelReductionFactorOutOfPlane = 1`:
```
(0051,1011) LO [p4]
```
whereas the CSA would lead one to expect to see:
```
(0051,1011) LO [p2s2]
```
Perhaps this was an early E11 release when SMS was still new and not given its own acceleration flag.

In general, dcm2niix assumes DICOM headers are consistent and truthful. We can always reverse the precedence between 0051,1011 and the CSA header. However, I would want to understand the reason for the conflict to make sure there are no unintended consequences.

**Comment by lukeje** [comment] 2023-01-26 22:03
I just checked a VE12U dataset recorded with a ported version of the sequence and the problem seems to remain there too, i.e. with GRAPPA 2×2 the string in the DICOM is: 
```
DICOM/SIEMENS CSA HEADER/ImaPATModeText: p4(string)
DICOM/SIEMENS CSA HEADER/PATModeText: p4(string)
``` 

This doesn't rule out that Siemens product sequences might have fixed the inconsistency in VE12, though; I'll check when I'm next at the scanner.

**Comment by neurolabusc** [comment] 2023-01-27 12:46
@lukeje please also take a look at [the validation series DKI_b2000_20_2p2mm_iPAT](https://osf.io/brvak/files/osfstorage) where the CSA slice timing clearly demonstrates a multi-band of two.

This is clearly noted in the tag 0051,1011:
```
(0018,1020) LO [syngo MR E11]            #SoftwareVersions
(0018,1030) LO [DKI_b2000_20_2p2mm_iPAT] #ProtocolName
(0051,1011) LO [p2 s2]                   #Private Tag & Data
```

However, the explicit SMS tag in the CSA header incorrectly suggests that the MultibandAccelerationFactor is 1:

```
sPat.lAccelFactPE	 = 	2
sPat.lAccelFact3D	 = 	1
```

This dataset appears to provide the opposite interpretation to yours, suggesting that precedence should be given to 0051,1011. Perhaps this reflects the custom CMRR sequences (ConsistencyInfo: `N4_VE11C_LATEST_20160120`), but it would be great to have an algorithm that works reliably for both product and research sequences.

**Comment by neurolabusc** [comment] 2023-01-27 12:58
@lukeje perhaps the issue here is the nomenclature for SMS acceleration of 2D EPI scans and 3D sequences. The BIDS specification clearly defines [MultibandAccelerationFactor](https://bids-specification.readthedocs.io/en/stable/glossary.html#multibandaccelerationfactor-metadata) for EPI scans, but does not (yet) define `ParallelReductionFactorOutOfPlane` that would be an analog of DICOM [0018,9155](https://dicom.innolitics.com/ciods/enhanced-mr-color-image/enhanced-mr-color-image-multi-frame-functional-groups/52009229/00189115/00189155). dcm2niix already defines a lot of DICOM tags that are [not in the BIDS standard](https://github.com/rordenlab/dcm2niix/tree/master/BIDS), so I am happy to add this while we lobby BIDS to include this one-to-one mapping.

The main thing I would want is some clarity regarding when we use the field `MultibandAccelerationFactor` and when we use `ParallelReductionFactorOutOfPlane`, along with validation datasets.

@mharms may have some thoughts on this.

**Comment by neurolabusc** [comment] 2023-01-27 13:34
The creators of the [Example dataset for the hMRI toolbox](https://www.sciencedirect.com/science/article/pii/S235234091930486X?via%3Dihub) should be admonished, as this provides an example of desired output without a reference input dataset. I am glad [BIDS now explicitly encourages `sourcedata` files](https://github.com/bids-standard/bids-website/pull/270/files). There has been a rampant creation of new BIDS fields that represent a wish list of desired sequence information with no consideration of how the user will determine this information, describing how different manufacturers use these terms, and validation datasets for regression detection. The opportunity for unintended consequences is profound. I worry that new BIDS fields are created by experts in sub-domains, but the burden of implementing them is pushed to users who do not have the expertise to decipher what is desired.

Perhaps your earlier link to a DICOM dataset is an attempt to rectify this situation. 

If you want these fields to be supported, I strongly encourage following the format of the [dcm_qa](https://github.com/neurolabusc/dcm_qa) series that provides explicit examples for usage such as [slice timing](https://github.com/neurolabusc/dcm_qa_stc), [enhanced DICOM](https://github.com/neurolabusc/dcm_qa_enh), and [gantry tilt](https://github.com/neurolabusc/dcm_qa_ct), and [ASL parameters](https://github.com/neurolabusc/dcm_qa_asl). These provide a one-to-one mapping from source DICOM images to expected BIDS results. Each commit of dcm2niix is tested with a battery of these validation datasets to avoid regressions, and this allows us to harmonize our use with other tools such as [dicm2nii](https://github.com/xiangruili/dicm2nii). The other advantage of these datasets is that they help identify gaps in the current DICOM specification, which allows us to work with manufacturers and the DICOM work groups to aid reproducible science.

**Comment by mharms** [comment] 2023-01-27 15:56
> @lukeje please also take a look at [the validation series DKI_b2000_20_2p2mm_iPAT](https://osf.io/brvak/files/osfstorage) where the CSA slice timing clearly demonstrates a multi-band of two.
> 
> This is clearly noted in the tag 0051,1011:
> 
> ```
> (0018,1020) LO [syngo MR E11]            #SoftwareVersions
> (0018,1030) LO [DKI_b2000_20_2p2mm_iPAT] #ProtocolName
> (0051,1011) LO [p2 s2]                   #Private Tag & Data
> ```
> 
> However, the explicit SMS tag in the CSA header incorrectly suggests that the MultibandAccelerationFactor is 1:
> 
> ```
> sPat.lAccelFactPE	 = 	2
> sPat.lAccelFact3D	 = 	1
> ```
> 
> This dataset appears to provide the opposite interpretation to yours, suggesting that precedence should be given to 0051,1011. Perhaps this reflects the custom CMRR sequences (ConsistencyInfo: `N4_VE11C_LATEST_20160120`), but it would be great to have an algorithm that works reliably for both product and research sequences.

@neurolabusc : I think there is a confusion in your earlier post.  I'm pretty sure that `sPat.lAccelFact3D` represents what is being called `ParallelReductionFactorOutOfPlane`, not the multi-band factor.
So, the validation series you were referencing would have GRAPPA = 2 x 1, with MB factor = 2.

**Comment by neurolabusc** [comment] 2023-01-27 16:20
@mharms yes, I realize that when I wrote my comment regarding 2D vs 3D data. So the `s` value of (0051,1011) encodes the product of sPat.lAccelFactPE and sPat.lAccelFact3D. This would provide some rationale for giving precedence to the CSA header when it is available.

This suggests we [extend the V* conversion](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#manufacturer-siemens-magnetic-resonance-imaging-v):
 - The  CSA series header (0029,1020) tag `sSliceAcceleration.lMultiBandFactor` is the V* analog for the BIDS field `MultibandAccelerationFactor`.
 - The  CSA series header (0029,1020) tag `sPat.lAccelFact3D` is the V* analog for `ParallelReductionFactorOutOfPlane`.

To be comfortable adding support for this, I would really like to have a concrete example where `ParallelReductionFactorOutOfPlane` and `ParallelReductionFactorInPlane` are modulated to document and replicate this interpretation. Since [support for Windows 7 has now ended](https://www.microsoft.com/en-us/windows/end-of-support), it would be great to see concrete examples for V*, [XA interoperability/classic](https://github.com/neurolabusc/dcm_qa_xa30) and [XA enhanced](https://github.com/neurolabusc/dcm_qa_xa30).

**Comment by mharms** [comment] 2023-01-27 16:29
Isn't it the `p` (not `s`) value of (0051,1011) that is giving the product of the two GRAPPA accelerations?

So, if I'm inferring correctly, `ParallelReductionFactorInPlane` is currently taken from the `p` value of (0051,1011), not from `sPat.lAccelFactPE` ?

**Comment by neurolabusc** [comment] 2023-01-27 16:30
@mharms, yes.

**Comment by mharms** [comment] 2023-01-27 19:18
I see that it's reported in some structural scans I have as `Enhanced` DICOMs from XA30:

>         (0018,9069) FD 2                                        #   8, 1 ParallelReductionFactorInPlane
>         (0018,9077) CS [YES]                                    #   4, 1 ParallelAcquisition
>         (0018,9078) CS [GRAPPA]                                 #   6, 1 ParallelAcquisitionTechnique
>         (0018,9079) FD 1000                                     #   8, 1 InversionTimes
>         (0018,9081) CS [NO]                                     #   2, 1 PartialFourier
>         (0018,9155) FD 1                                        #   8, 1 ParallelReductionFactorOutOfPlane

None of these (0018,9***) field are included in `Classic` DICOMs exported from the same scanner.

I don't know if it adds anything, but there is a `sPat.dTotalAccelFact` field, which I assume is just the product of `sPat.lAccelFactPE` and `sPat.lAccelFact3D`.

**Comment by lukeje** [comment] 2023-01-27 21:38
Hey Chris, I would appreciate it if you stopped [tilting at windmills](https://en.wikipedia.org/wiki/Don_Quixote#Tilting_at_windmills). I have made a targeted bug report and would appreciate it if you remained on topic. As has become clear, the current behaviour of dcm2niix does not match what would be expected.

You are correct that the dataset I am currently converting is related to me trying to prepare a dataset for you in relation to a [previous bug report](https://github.com/rordenlab/dcm2niix/issues/646). However the extra fields that were requested there are not relevant here. Indeed, I hope that we (and other members of the hMRI toolbox development team) can work together to include the extra fields from the qMRI "wishlist" in future, after further communication.

**Comment by neurolabusc** [comment] 2023-01-29 13:46
@lukeje I only have a single exemplar, so I would be grateful if can you test out the latest commit to the development branch (v1.0.20230127). It uses the new BIDS tag `ParallelReductionFactorOutOfPlane` instead of the previous `ParallelReductionOutOfPlane` instead of `AccelFact3D` (if from the CSA) or `ParallelReductionOutOfPlane` (if from 0018, 9155 or 0043,1083). The CSA values are given precedence over (0051,1011).

You can get a pre-compiled copy by [selecting the desired operating system  and then artifact from AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix), or build it yourself with UNIX:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

**Comment by neurolabusc** [comment] 2023-01-29 13:59
@mr-jaemin can you please test the behavior of the latest commit. I assume that I use the **reciprocal** of the second item in the [0043,1083](https://github.com/rordenlab/dcm2niix/tree/master/GE) for `ParallelReductionFactorOutOfPlane`. This is related to your help with [issue 641](https://github.com/rordenlab/dcm2niix/issues/641). 

The exemplar I have is [the T1 scan from dcm_qa_ge](https://github.com/neurolabusc/dcm_qa_ge/tree/master/In/05_3D_Ax_T1_MP_RAGE_R22) which reports
```
(0043,1083) DS [0.5\0.5]
```
which I assume converts to BIDS:
```
"ParallelReductionFactorInPlane": 2,
"ParallelReductionFactorOutOfPlane": 2,
```

**Comment by mr-jaemin** [comment] 2023-02-01 16:12
I collected different combinations of `ParallelReductionFactorInPlane` (Acceleration-> Phase) `ParallelReductionFactorOutOfPlane` (Acceleration-> Slice) on GE as shown below
![Screen Shot 2023-02-01 at 9 20 03 AM](https://user-images.githubusercontent.com/72111485/216091507-25242842-264d-4a25-b7e0-1a33ac68f7f1.png)

For completeness, I also collected a dataset with Acceleration -> HyperSense (Compressed Sensing) (although this is off the topic for this particular issue)
![Screen Shot 2023-02-01 at 9 27 05 AM](https://user-images.githubusercontent.com/72111485/216093000-d29c2831-7273-4d79-a605-7e9f99375ad4.png)

Here is the list of scans, where `P`: Phase, `S`: Slice, `H`: HyperSense
![Screen Shot 2023-02-01 at 9 40 01 AM](https://user-images.githubusercontent.com/72111485/216093128-0e79320a-9c79-4e3c-9de3-acfc2e994596.png)

I confirmed that everything is working as expected. 
For example,  09_T1_MPRAGE_P1.2S1.44 reports
```
(0043,1083) DS [0.833333\0.694444]                      #  18, 2 AssetRFactors
```
which converts to BIDS
```
	"ParallelReductionFactorInPlane": 1.2,
	"ParallelReductionFactorOutOfPlane": 1.44,
```

The stable release of dcm2niix (v1.0.20220915), as expected, reports `Acceleration-> Slice` as `ParallelReductionOutOfPlane`, not `ParallelReductionFactorOutOfPlane`
```
	"ParallelReductionFactorInPlane": 1.2,
	"ParallelReductionOutOfPlane": 1.44,
```
Perhaps, I will discuss with Chris separately about `HyperSense`'s Acceleration factor (as shown below) and how to these exemplars.
```
(0043,10b7) LO [1.24\1\10\0]                            #  12, 4 Compressed Sensing Parameters
```

**Comment by neurolabusc** [comment] 2023-02-07 15:07
@mr-jaemin thanks. Closing this issue as it passes all samples provided. I will deal with compressed sensing and deep learning in a future issue when I have samples from other vendors.

**Closed by neurolabusc** 2023-02-07 15:07 UTC

**Comment by lukeje** [comment] 2023-02-12 16:12
> I would be grateful if can you test out the latest commit to the development branch (v1.0.20230127).

Sorry for the late reply; yes, the new development branch works as expected.

Thanks a lot!
