### ISSUE TITLE
An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by TamerGezici** [rordenlab/dcm2niix#609] opened 2022-06-04 20:46 UTC
Dear all,

I know this is a duplicate of an earlier issue but the issue persists.

Running `results = converter.run() `on latest python 3.10 with nipype on a windows 10 machine on a jupyter notebook threw an error:
`[WinError 10038] An operation was attempted on something that is not a socket 220604-23:39:02,628 nipype.interface`

Interestingly, the conversion does happen. The files are there. It's just that there is an error like this.

For now I threw a try except to prevent the error breaking my code. However, it would be useful to have proper fix if possible.

Thanks.

**Comment by neurolabusc** [comment] 2022-06-05 11:07
This forum is for questions regarding dcm2niix. I suspect that dcm2niix will work fine from the command line or the [MRIcroGL](https://github.com/rordenlab/MRIcroGL/releases) graphical interface (the Import/ConvertDICOMtoNIfTI menu item).

Your question seems appropriate for the [nipype](https://github.com/nipy/nipype) forum. Indeed, it may be a [duplicate of reported issues])https://github.com/nipy/nipype/issues/3302) regarding support for the [Windows operating system](https://github.com/nipy/nipype/issues/3277).

**Closed** 2022-06-05 11:09 UTC
