### ISSUE TITLE
Philips enhanced vs classic - different positioning of image

### ISSUE THREAD

**Issue by baxpr** [rordenlab/dcm2niix#507] opened 2021-04-15 16:25 UTC
**Describe the bug**
We have (somehow) cajoled one of our scanners into producing both the usual classic series (26k files) and an enhanced DICOM of the same series. When the .nii produced by v1.0.20210317 are viewed in fsleyes, the image position is different by one voxel in the left/right dimension. The qform/sform of the two nifti files are the same.

**To Reproduce**
dcm2niix v1.0.20210317, no options

**Expected behavior**
I'd expect identical niftis for the two dicoms.

**Output Log**

    ImagePositionPatient:
    Enhanced first frame: -114.55773750040  -156.50354454573  -5.1988021554425
    Classic first frame:  -114.5577375004   -156.50354454573  -5.1988021554425

** Version (please complete the following information):**
Chris Rorden's dcm2niiX version v1.0.20210317  Clang12.0.0 x86-64 (64-bit MacOS)

Most recent commit on development branch is ccf263d - it produces the same result.
Chris Rorden's dcm2niiX version v1.0.20210403  Clang12.0.0 x86-64 (64-bit MacOS)

**Comment by neurolabusc** [comment] 2021-04-16 13:27
@baxpr please confirm this is fixed in the latest commit to the development branch. The issue was specific to enhanced DICOM images that store extremely large and verbose headers.

The issue is that the [NIfTI header](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) stores vox_offset (offset from start of file to image data) as a 32-bit (`single precision`) floating point value. Floats have [poor accuracy](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/company/newsletters/news_notes/pdf/Fall96Cleve.pdf) for large integers.

In Matlab:
```
>> f32 = single(53543146)
f32 =
  single
    53543144
```

The analogous C code (which prints `53543146 -> 53543144.00`):

```
uint32_t ii = 53543146;
float fi = ii;
printf("%d -> %8.2f\n", ii, fi);
```

The updated code uses an integer to store the DICOM voxel offset.

**Comment by baxpr** [comment] 2021-04-16 13:36
@neurolabusc wow, that's pretty out there. Yet another fun quirk of our recent forays into multiband fmri. Results from the d8a46aa look good to me - I get matching .nii from either set of DICOM. I get one difference in the files, here, don't know its significance:

```
$ cmp -b classic/*nii enhanced/*nii
classic/classic.nii enhanced/enhanced.nii differ: byte 163, line 2 is  61 1  60 0
```

**Comment by neurolabusc** [comment] 2021-04-16 14:32
An offset at 163 would be in the [`descrip`](https://brainder.org/2012/09/23/the-nifti-file-format/) text field. You could use fslhd to report this value. It should look something like `TE=35;Time=152005.26` and any differences presumably reflect round errors in different DICOM header forms fro these values.

**Comment by baxpr** [comment] 2021-04-16 14:43
Just so. Thanks!

```
descrip		TE=35;Time=152120.880
descrip		TE=35;Time=152005.260
```

**Closed** 2021-04-18 13:26 UTC
