### ISSUE TITLE
PET json sidecar for BIDS : RadionuclideTotalDose versus InjectedRadioactivity

### ISSUE THREAD

**Issue by arovai** [rordenlab/dcm2niix#669] opened 2023-01-18 19:51 UTC
**Describe the bug**

Converting dicom for PET data in view of BIDS validation requires a "InjectedRadioactivity" field in sidecar json file:

``"InjectedRadioactivity": 323589984,``

But dcm2niix doesn't write this field. 
The closest match is "RadionuclideTotalDose":

`"RadionuclideTotalDose": 323589984,`

This value seems to match what is meant by "InjectedRadioactivity" (tested by reading dicom headers "by hand" using pydicom).

**To reproduce**

1. Run the command 'dcm2niix ' on PET dicom (tested for data taken from a GE signa PETMR).
2. Inspect the produced json.

**Expected behavior**

json must have "InjectedRadioactivity" field with the content of the dicom tag  0018, 1074  (as per [BIDS documentation](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html)).

**Version**

dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC9.3.0 x86-64 (64-bit Linux)

BIDS validation with v1.9.9 (latest).

**Comment by neurolabusc** [comment] 2023-01-18 20:51
This discrepancy is historical, as dcm2niix started including PET fields before [BEP009](https://bids.neuroimaging.io/get_involved). This is why the dcm2niix documentation describes all the [PET](https://github.com/rordenlab/dcm2niix/tree/master/BIDS#modality-positron-emission-tomography) fields as being defined by dcm2niix and not BIDS. Typically when there is a one-to-one mapping between the DICOM tags and a BIDS field, they will have the same name. This was the approach I took when I added support, using the formal DICOM name:

 - [Radionuclide Total Dose (0018,1074)](https://dicom.innolitics.com/ciods/nm-image/nm-isotope/00540016/00181074)
 - [Convolution Kernel (0018,1210)](https://dicom.innolitics.com/ciods/ct-image/ct-image/00181210)
 - [Attenuation Correction Method (0054,1101)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541101)
 - [Decay Correction (0054,1102)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541102)
 - [Reconstruction Method (0054,1103)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541103)
 - [Decay Correction Factor (0054,1321)](https://dicom.innolitics.com/ciods/pet-image/pet-image/00541321)

I am not sure why the BEP009 committee decided to coin their own terms. Perhaps they felt their choices were more explicit. Perhaps it reflects the fact that most of the committee used systems that generated ECAT rather than DICOM format images. 

I note that [PET2BIDS](https://github.com/openneuropet/PET2BIDS/blob/419412c3ca5c8f0c03f70bf2e3bcc82c34b8cd24/metadata/dicom2bids.json#L2) maps DICOM names (dcmfields) to BIDS names (jsonfields).

I am not a PET expert, and do not have access to PET equipment.  However, I have spent a lot of time on this, including going to the [DICOM WG-3](https://www.dicomstandard.org/activity/wgs/wg-03) meetings. One lesson I learned is that the manufacturers do not have complete control over the what is injected, and therefore they feel it would be inappropriate to generate values in the DICOM files that they can not verify. Therefore, the PET images do not contain sufficient information for analysis. For this reason, dcm2niix wrappers like [PET2BIDS](https://github.com/openneuropet/PET2BIDS) play a vital role in allowing you to create archive quality datasets suitable for automated analyses and replication.

@CPernet do you agree that dcm2niix should adopt the BIDS terms as @arovai suggests, or is this the remit of PET2BIDS? It would be great to provide a [dcm_qa](https://github.com/neurolabusc/dcm_qa) repository that provides both DICOM input images and the expected BIDS output. Every commit of dcm2niix is tested against several dcm_qa repositories to identify regressions.

**Comment by CPernet** [comment] 2023-01-20 07:18
Ultimately it's up to you Chris to decide if you rather export with the DICOM or BIDS field name.
-- the mapping is now in the spec but also in [this json file](https://github.com/openneuropet/PET2BIDS/blob/main/metadata/dicom2bids.json). Note the wrapper should keep working after updates because it reads fields and update as needed (ie if dcm2niix now output a new BIDS field then no mapping takes place).

In a few cases, it is trivial but in most, it isn't. If we take the dose aspect, they are simply too many variations and options - to such an extent we have [a dedicated function](https://pet2bids.readthedocs.io/en/latest/matlab.html#matlab.check_metaradioinputs) just to handle that! and when it comes to reconstruction is probably worse .... indeed in general there are two many factors that are not in the header.  

@arovai please try our wrapper (matlab or python, both the same)  and let us know if there is anything that doesn't work 
thx for tagging me in here chris

**Comment by neurolabusc** [comment] 2023-01-20 15:45
Thanks @CPernet and @captainanova. I will close this issue and I will not change the behavior. The PET2BIDS wrapper provides a lot of added value for those users working with PET. As I noted, by design PET DICOMs are underspecified for BIDS, so PET2BIDS fills a niche beyond the remit of dcm2niix.

**Closed by neurolabusc** 2023-01-20 15:45 UTC

**Comment by mharms** [comment] 2023-01-24 14:44
FWIW, if BIDS is defining new tags, and the analogous tags already exist as part of the output of `dcm2niix`, I think that the BIDS specification should give strong preference to simply adopting the tag names used by `dcm2niix`, which as @neurolabusc notes, frequently adopts the name used by the DICOM standard itself.  That is to say, more of the burden of harmonization/conformance should fall on BIDS, than `dcm2niix`.

**Comment by neurolabusc** [comment] 2023-01-26 12:45
@mharms preferences are now reflected in the bids standard [thanks to this amendment](https://github.com/bids-standard/bids-website/pull/270#issuecomment-1404754353).
