### ISSUE TITLE
Slicing timing longer than TR in CMRR sequence

### ISSUE THREAD

**Issue by XinyuLiu1999** [rordenlab/dcm2niix#656] opened 2022-11-28 10:51 UTC
Hello,

I am coming back from a previous neurostar post ( [https://neurostars.org/t/bids-error-code-66-slice-timing-error/23247](url) ) since I forgot to follow-up lately (sorry for that!)
The problem is that for our resting-state fMRI image acquired using CMRR at 7T, the slicing timing in the JSON file generated by dcm2niix is longer than TR and thus result in failure when converting to BIDS (Code 66 SLICETIMING_VALUES_GREATOR_THAN_REPETITION_TIME**).

**To reproduce**

The data can be downloaded here: [https://drive.google.com/file/d/1ICHPYRhI7BksCovlsAiGE87c4zUl7Io4/view?usp=sharing](url)

**Version**

dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)

Thank you very much.

**Comment by neurolabusc** [comment] 2022-11-28 13:11
dcm2niix assumes that the DICOM files are truthful. Your DICOM images report the slice times for the single band reference image rather than the acquired multiband data. This is not a limitation of dcm2niix, rather it reflects that the DICOMs report incorrect values. You are using the experimental CMRR sequences on Siemens software VB17. Your issue may be a duplicate of a  [resolved issue with CMRR sequences](https://github.com/CMRR-C2P/MB/issues/29). Perhaps a software upgrade is required. Alternatively, you can create [CMRR C2P issue](https://github.com/CMRR-C2P/MB/issues). The difference between your data and the previously reported CMRR issue is that all of your volumes show the incorrect values, not just the first one. Due to this bug, dcm2niix reads slice times from the 2nd volume in a series.

**Closed** 2022-12-05 14:53 UTC
Labels: acknowledged
