### ISSUE TITLE
Error: Anatomical Orientation Type (0010,2210) is QUADRUPED: rotate coordinates accordingly

### ISSUE THREAD

**Issue by Microdeep-ZL** [rordenlab/dcm2niix#666] opened 2023-01-11 09:30 UTC
When I attempted to convert rat MRI images from dicom to nifti, I saw this error. However, the conversion was done successfully and the nifti images looked good. But I'm still worried whether it's truly done successfully as it appeared. It said "rotate coordinates accordingly", but what exactly did the script do with the coordinates?

Thanks for your kind help!

**Comment by Microdeep-ZL** [comment] 2023-01-11 09:40
I examined the images in ITK-SNAP. They look pretty much the same, except the slice number at upper left.
![Picture1](https://user-images.githubusercontent.com/58393754/211771595-b6533a0d-5864-44a2-bbb0-d37c7c90d82c.png)

**Comment by neurolabusc** [comment] 2023-01-11 09:47
ITKsnap shows the issue very clearly: note that the coronal slice has the vertical inferior->superior direction listed as A->P and the sagittal slice lists the vertical posterior->anterior dimension as I->S. While there is a clear convention regarding NIfTI coordinates for bipeds (X increases rightward, Y increases anteriorly and Z increases superiorly), there is inconsistent use in quadrupeds. If the software tools and templates match the output of dcm2niix, all should work well. Just be aware that tools like ITKsnap are mis-labelling the directions.

**Comment by Microdeep-ZL** [comment] 2023-01-12 07:25
> the coronal slice has the vertical inferior->superior direction listed as A->P

Do you mean that "the coronal slice (at upper left) has the vertical inferior->superior direction listed as P->A"?

>Just be aware that tools like ITKsnap are mis-labelling the directions.

I know the original DICOM files have wrong orientation (even the left/right). But I also found that, ITK-SNAP says the DICOM and NIfTI files have different orientation, as shown in the figure. if ITK-SNAP is mis-labelling the directions, do you have any recommendation to view the images and directions correctly?
![Picture1](https://user-images.githubusercontent.com/58393754/212003423-654d6026-c0a5-46ea-9037-b2bfc07d2e61.png)

**Comment by Microdeep-ZL** [comment] 2023-01-12 07:28
![Picture1](https://user-images.githubusercontent.com/58393754/212003832-e3935e4e-1cc7-45ea-a5d5-fc6da6e19c6b.png)

**Comment by neurolabusc** [comment] 2023-01-12 11:55
Your statement `I know the original DICOM files have wrong orientation` is incorrect, the DICOM files are correct. It is the DICOM viewers and converters (Horos, ITK, dcm2niix, etc.) that are *all* wrong in failing to handle the DICOM [Anatomical Orientation Type  (0010,2210)](https://dicom.innolitics.com/ciods/12-lead-ecg/general-series/00102210) tag. The dcm2niix warning is alerting you that it is ignoring this tag to maintain compatibility with other tools. It is fine if all tools are wrong as long as they are wrong together and they match the expectations of your subsequent processing tools. Therefore, you as a user need to make sure that the [atlases and templates you choose](https://www.nitrc.org/projects/whs-sd-atlas) are aware of the behavior of your converters.

@effigies as the BIDS maintainer, it may be worth clarifying the terminology for X,Y,Z space for quadrupeds. In particular with projects like [fmriprep-rodents](https://github.com/nipreps/fmriprep-rodents).

**Comment by neurolabusc** [comment] 2023-01-12 16:39
The change in LSP to LIP is the [expected behavior](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). Voxel based data is saved as columns (i), rows (j) and slices (k). The DICOM coordinate system has the first row at the top of the screen, with later rows descending down the screen, the way we right text in English with the first line at the top of the page. On the other hand, the NIfTI coordinates have j increasing as we move up the screen, the same way we draw a graph with cartesian coordinates where moving up the screen means an increase in the values of the y axis. This transform is stored in the NIfTI sform, so you will note that the S/I labels in ITKsnap are consistent regardless of NIfTI or DICOM coordinates.

**Comment by effigies** [comment] 2023-01-12 19:49
If I'm reading C.7.6.2.1.1 correctly, then the DICOM orientation is always LPS+ for bipeds and LSA+ for quadrupeds, but all DICOM converters and tooling make a hard assumption of LPS+. So if you convert without adjusting, NIfTI tools will show the inferior-superior axis and label it anterior-posterior, and display posterior-anterior while labeling it inferior-superior.

Looking at the screenshots above, it seems I've gotten that wrong; I'm not sure if I'm reasoning incorrectly or there's an implicit conversion that I'm failing to account for.

What is the proposal for BIDS here? That we note that for rodents instead of encoding RAS+ world coordinates, that the affine targets may be RIP+ (or something else...)? Does this conform with how data saved to Bruker formats instead of DICOM are saved? If converters from different formats interpret NIfTI world coordinates differently, we're going to need some way of identifying the space.

I will need to tag in @eilidhmacnicol and @thechymera for fmriprep-rodents and Bruker expertise.

**Comment by Microdeep-ZL** [comment] 2023-01-13 08:31
>Your statement I know the original DICOM files have wrong orientation is incorrect

The data were collected by our team. We selected the animal position as "supine" while it was actually "prone". Hence, the orientation in DICOM files are bound to be wrong. Thank you so much for your reply!

**Comment by neurolabusc** [comment] 2023-01-13 10:04
@Microdeep-ZL thanks for clarifying. This error could impact the encoding of L:R and A:P, but not the fact that the A:P and I:S labels are swapped which is due to tools and viewers ignoring Anatomical Orientation Type (0010,2210). I am unfamiliar with animal imaging acquisition or processing. The NIfTI rodent templates I have seen seem to all map the X+,Y+ and Z+ directions to anatomical R, A, S but this is not the behavior of DICOM viewers or converters. Perhaps this is always handled by processing tools.

**Comment by neurolabusc** [comment] 2023-01-14 21:16
Closing this issue. I do not have expertise in quadruped studies. Happy to revisit if BIDS specifies expected behavior.

**Closed by neurolabusc** 2023-01-14 21:16 UTC

**Comment by TheChymera** [comment] 2023-01-16 14:45
Sadly I do not integrate conversion to (and then from) DICOM in my workflows, so I might not have much insight into this.

What I can say, is that generally
> We selected the animal position as "supine" while it was actually "prone". Hence, the orientation in DICOM files is bound to be wrong.

Does not hold true for my PV→NIfTI workflow. Bruker PV systems were designed in the hope of being used with non-human primates (which usually lie supine), so as long as you are using sequences derived from the ones shipped by the scanner, supine is in fact the correct option to use when the mouse is prone. It makes no sense, I know, the best way to visualise it is to think that if the mouse was a tiny monkey, the brain would be pointing in the precisely opposite direction as that of a monkey.

**Comment by neurolabusc** [comment] 2023-01-16 19:08
@TheChymera thanks. The challenge is that for bipeds the dorsal-ventral and caudal-rostral dimensions are different for the head versus the rest of the body, while for quadrupeds these are consistent. Whenever I look at quadruped DICOM brains converted with Horos, ITK, dcm2niix they seem to require a 90-degree rotation to match popular quarupded templates such as [here]( https://resource.loni.usc.edu/resources/atlases-downloads/), [here](https://www.nitrc.org/projects/sigma_template), [here](https://www.nitrc.org/projects/tpm_mouse) and [here](https://www.nitrc.org/projects/incfwhsmouse) 

I recognize many quadruped scientists are used to publishing images where the sagittal slices show the [anterior-posterior dimension](https://doc.pmod.com/pnrod/wistarratbrainatlastohoku8102.html) as vertical, whereas for bipeds I am used to sagittal slices showing AP as the horizontal direction. 

It is outside my expertise, but it is unclear to me what the consensus is in the quadruped world and that all tools deal with the data created by dcm2niix consistently.

![biped_quadruped](https://user-images.githubusercontent.com/8930807/212749125-754d94e8-1e37-4f00-9841-8239aea43e38.png)

**Comment by Microdeep-ZL** [comment] 2023-01-17 01:20
Thank you for both your efforts! I was trying to reorient our images to align with SIGMA rat bain template. And when converting to NIfTI with dcm2niix, I saw the error message. I didn't know whether it did anything to the reorientation behind the scenes. 

Thanks to your help, now I have figured out how to do the reorientation. What I found is
- When displaying quadruped DICOM, ITK-SNAP shows ventral/dorsal as anterior/posterior and rostral/caudal as superior/inferior. dcm2niix keeps that relation, even with that error message "rotate coordinates accordingly". 
- SIGMA rat brain template shows ventral/dorsal as inferior/superior and rostral/caudal as anterior/posterior.
- Even if we scan the rat in prone position and select the animal position also as prone, we still have to do the reorientation, because SIGMA rat brain template interprets V/D/R/C as A/P/S/I differently.

**Comment by TheChymera** [comment] 2023-01-17 13:04
@Microdeep-ZL Do you only have the data as DICOM? Have you considered converting it directly to nifty? If so, you could upload it and I can have a look. It could also be that the template is oriented incorrectly. Sometimes templates have incorrect data matrix orientations which they then “fix” by setting negative numbers in the affine.

So if you need assistence, I'd recommend:

* Upload a NIfTI file of *your* data so we can check whether it looks ok.
* Try to download one of the templates which I've compiled here (their orientations are fine) and try to register to those → https://gitlab.com/FOS-FMI/rat-brain-templates_generator#rat-brain-templates-package-releases

Additionally (in case you don't already know all of this), I've written down most of the challenges I faced in getting images to line up with templates in 1.1, 1.2, and 1.3 [here](https://www.sciencedirect.com/science/article/pii/S1053811921006625?via%3Dihub#sec0001).

**Comment by neurolabusc** [comment] 2023-01-17 13:30
Since the rotation is 90-degrees, a simple Python or Matlab script could adjust the transforms. If you only have a small number of scans, you can do this manually using the graphical user interface of MRIcroGL function Import/Tools/Rotation. Indeed, you can use the graphical tool once to work out the sform transformation required for your Python or Matlab script. As an added bonus, for Unix (Linux, MacOS users), MRIcroGL will also report a 3D vector of the matrix permutation (dimension, with negative indicating a mirror flip) consistent with Matlab [notation](https://stackoverflow.com/questions/12787475/matlabs-permute-in-python):
```
Reorient Dimensions 1 3 2
```
![rotate](https://user-images.githubusercontent.com/8930807/212911474-42455bae-d421-4b53-94cf-6f9e601949ca.png)

**Comment by eilidhmacnicol** [comment] 2023-01-17 18:11
I appreciate this issue is closed, but I thought I'd chime in with my two cents (even though encoding orientations still makes my head hurt) because I'm glad to see the conversation happening around inconsistent naming nomenclature for orientation in rodent imaging.

Similar to @TheChymera, I also have limited experience here because our group also don't convert to nii from dcm; we use a converter built for Bruker's 2dseq format (e.g. [brkraw](https://github.com/BrkRaw/brkraw)). We have found that this converts our data, which is recorded as prone when the rodent is prone, to an orientation that matches that of the SIGMA atlas shared above. Importantly, this does not necessarily change how the data is stored (i.e. the AP axis might not be the second dimension of the data matrix) but it is accounted for reliabily in the affine and header information.

>  It could also be that the template is oriented incorrectly. 
Based off what I said above, I think the idea of 'incorrect' here is contextual. The SIGMA labels are oriented so that they are anatomically correct, which in my opinion is more meaningful and easier to interpret for the user than if they are oriented relative to what the brain would look like if it was a small monkey. I note that the SIGMA atlas was also acquired with paravision, but converted to .nii with matlab scripts. Maybe @DavidBarriere could give us a little more information about how the data were converted (and consequently how they handled the orientation) for the SIGMA atlas?

Essentially, quadruped labelling in nifti images seems to wholly depend on a) the original image format and b) the converter used and c) whether the scanning orientation (i.e. prone vs supine) is accurately recorded.

As far as fmriprep-rodents, we are intentionally not prescribing data conversion because the mixture of these three factors is beyond the scope of the project. Instead, the input data is expected to be nifti and in such a format that nibabel's orientation tools can reliably adjust the orientation to match another. By this I mean that passing an affine matrix to `aff2axcodes` produces labels that match the data matrix. Thus, the codes may not necessarily be RAS, but at least we can adjust it to other atlases/template spaces easily. In the case of the dicom-converted images presented in this thread, the `aff2axcodes` would likely not be reliable since the SI and AP axes are swapped.

Sorry I can't be more help, but I'm sure this conversation will be fruitful!

**Comment by Microdeep-ZL** [comment] 2023-01-18 14:34
@neurolabusc Thanks for your advice! I reoriented the images through `fslorient`. I first get the sform with `fslorient -getsform`, and then do a matrix multiplication. After that I use `fslorient -setsform` and `fslorient -copysform2qform` to set new sform and qform. After being reoriented in this way, the quality control report from [RABIES](https://github.com/CoBrALab/RABIES) preprocessing looks normal. In addition, ITK-SNAP also has a similar GUI for reorientation. 

@TheChymera We always convert DICOM to NIfTI (using dcm2niix) before any preprocessing and analysis. Great thanks for your kindness, but there would be a lot of paperwork to do before data sharing. Anyways, we have basically solved the reorientation problem.

>I note that the SIGMA atlas was also acquired with paravision, but converted to .nii with matlab scripts.

@eilidhmacnicol Thanks for the information. 

>Essentially, quadruped labelling in nifti images seems to wholly depend on a) the original image format and b) the converter used and c) whether the scanning orientation (i.e. prone vs supine) is accurately recorded.

I totally agree. In addition, I think only two things are important for orientation in rodent brain. 1) Left/Right must be correct 2) Get other orientations consistent in brain atlas and user's images

Glad to have the conversion with you all. Thanks again!

**Comment by Microdeep-ZL** [comment] 2023-01-18 14:49
@TheChymera I downloaded the WORD atlas from the website you provided. Our images would have the same orientation if the animals were scanned in prone position and we also selected the animal position as "prone" in Paravision software. From my understanding of [DICOM specification](https://dicom.innolitics.com/ciods/12-lead-ecg/general-series/00102210#:~:text=the%20patient%27s%20orientation.-,If%20Anatomical%20Orientation%20Type%20(0010%2C2210)%20is%20absent%20or%20has%20a%20value,the%20cranial%20(as%20opposed%20caudal)%20side%20of%20the%20proximal%20limbs%2C%20and,-the%20z%2Daxis), 
- quadruped's Dorsal = biped's Posterior
- quadruped's Rostral = biped's Superior

I think this relation should be what you meant by "correct orientations", is it?

**Comment by DavidBarriere** [comment] 2023-01-18 16:25
Hi everybody.
Critical questions...
Basically, our matlab code works more or less in the same way than dcm2niix and provide similar orientations. Data for SIGMA creation have been acquired as prone position onto the 11.7T bruker magnet running on PV6.
However, data have been reoriented to match with classical viewers display conventions. Namely, left-right/anterior-posterior/ dorsal-ventral orientations according to the rostro-caudal orientation of the rat brain for anterior-posterior direction (which is biologically meaningfull).
Before publication, we checked with several viewers (namely: MRICron, anatomist, fsleyes, itksnap and SPM) that SIGMA was consistently displayed in the same way (and it was).
Hence I don't think I'm wrong in stating that the SIGMA template and atlas are "well oriented" but accordingly to the viewers. convention.
According to your previous image with MRIcron: 1/ within the saggital plane, S and I are (S)uperior (top, dorsal) and (I)nferior (bottom, ventral). In the axial plan A and P (A)nterior (rostral, nose), (P)osterior (caudal, tail). 

Eventually, the AP plan cross both anterior and posterior commissures (AC/PC) to deliver a final orientation close to the Paxinos.

Best  

![212790304-f41df500-4533-4473-921c-d4542e83fe2e](https://user-images.githubusercontent.com/101575749/213219043-6584a750-bf3b-47a9-a1e1-1b163e1f7f11.png)

**Comment by sabinevater** [comment] 2024-01-20 18:29
Hi everybody, 

thank you very much for all your comments and the great discussion. 
Just to make sure I understand correctly: when converting DICOMs with an anatomical orientation type of quadruped are converted to Nifti we get the message "rotate coordinates accordingly". Does this mean the images were rotated by dcm2niix during the conversion or is it only a warning that we should have rotations in mind?

Thank you very much in advance and kind regards!

**Comment by Microdeep-ZL** [comment] 2024-01-20 18:32
Based on my experience, the left/right orientation is maintained when opening DICOM and NIfTI in ITK-SNAP.

**Comment by neurolabusc** [comment] 2024-01-21 13:49
@sabinevater I do not have access to Bruker equipment, though I have received sample images. Until someone spends the time exhaustively checking the conversions, I would be particularly careful that the diffusion .bvec files store the correct orientation, you can test this yourself for your sequence based on [this document](https://www.nitrc.org/docman/?group_id=880). You may also want to employ [GradFlipTest](https://afni.nimh.nih.gov/pub/dist/doc/program_help/@GradFlipTest.html).

**Comment by Microdeep-ZL** [comment] 2024-01-24 02:25
For diffusion images, Bruker dicom doesn't have the information of bvecs or bvals. As far as I know, it's not in DICOM generated by ParaVision 6.0.1. There could be diffusion information in later versions of ParaVision.

Rostral/Caudal/ventral/dorsal are easy to identify for the brain image. A simple way to check left/right may be putting something (eg. a vitamine E capsule) on one side of the head and check if the left/right is properly interpreted. We used this way and confirmed that, dcm2niix maintains the left/right between the source DICOM and the output NIfTI.

**Comment by neurolabusc** [comment] 2024-01-24 13:05
@Microdeep-ZL the modern Bruker DICOMs (e.g. ParaVision 360) do store bvec/bval files using the [recommended public tags](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI), specifically `DiffusionBValue` (0018,9087) and `DiffusionGradientOrientation` (0018,9089). dcm2niix will use this to generate FSL/BIDS-compatible bvec and bval files:

```
(0008,0060) CS [MR]                                     #   2, 1 Modality
(0008,0070) LO [Bruker BioSpin MRI GmbH]                #  24, 1 Manufacturer
(0018,1020) LO [Acquisition PV-360.3.5\ParaVision 360.3.5] #  42, 2 SoftwareVersions
(0018,9075) CS [BMATRIX]                                #   8, 1 DiffusionDirectionality
(0018,9076) SQ (Sequence with undefined length #=1)     # u/l, 1 DiffusionGradientDirectionSequence
  (fffe,e000) na (Item with undefined length #=1)         # u/l, 1 Item
    (0018,9089) FD -0.81079198695109191\-0.14296450304170301\0.56760682233914199 #  24, 3 DiffusionGradientOrientation
  (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
(fffe,e0dd) na (SequenceDelimitationItem)               #   0, 0 SequenceDelimitationItem
(0018,9087) FD 90.309984256159197                       #   8, 1 DiffusionBValue
(0018,9601) SQ (Sequence with undefined length #=1)     # u/l, 1 DiffusionBMatrixSequence
  (fffe,e000) na (Item with undefined length #=6)         # u/l, 1 Item
    (0018,9602) FD 3.9142834511963901                       #   8, 1 DiffusionBValueXX
    (0018,9603) FD 10.277992312030101                       #   8, 1 DiffusionBValueXY
    (0018,9604) FD -15.249061155588                         #   8, 1 DiffusionBValueXZ
    (0018,9605) FD 26.987740834571401                       #   8, 1 DiffusionBValueYY
    (0018,9606) FD -40.0409158661113977                     #   8, 1 DiffusionBValueYZ
    (0018,9607) FD 59.407959970391403                       #   8, 1 DiffusionBValueZZ
  (fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
(fffe,e0dd) na (SequenceDelimitationItem)               #   0, 0 SequenceDelimitationItem
(fffe,e00d) na (ItemDelimitationItem)                   #   0, 0 ItemDelimitationItem
```

However, the DICOM directions are in world space, while the FSL coordinates must use image coordinates (with the X-component flipped if the corresponding NIfTI file has a positive determinant. While many people have validated dcm2niix for bipeds scanned head first supine, I do not think dcm2niix has been tested with other orientations. While I have sample datasets, I have not had the time to explore this, hence [issue 761](https://github.com/rordenlab/dcm2niix/issues/761). Happy to assist someone who wants to take the lead in this (@TheChymera this may be something you would be interested in).
