### ISSUE TITLE
Philips PAR/REC failure - negative slice gap?

### ISSUE THREAD

**Issue by baxpr** [rordenlab/dcm2niix#273] opened 2019-02-20 17:50 UTC
@neurolabusc not sure if you're trying to stay on top of PAR/REC stuff but I've got some new Philips PAR/RECs that the most recent release v1.0.20181125 can't handle. At first glance I'd guess it's due to a negative value in the slice gap field. I can provide an example if you like. The PAR file specifies "gap -2.5". The XML file specifies "SliceGap 0.0". So there may be some issue upstream.

dicm2nii does work with these files, so there is an alternative.

**Comment by neurolabusc** [comment] 2019-02-21 00:21
@baxpr the issue is clearly with the PAR/REC files. As you note, viewing the PAR header with a text editor reveals
```
thick   gap 
2.500 -2.500
```
dcm2niix always assumes the header is truthful. I have submitted a simple kludge that should fix your issue: it measures the distance between slices using the slice position columns. If there is a discrepancy between the slice thickness + gap versus what is computed using slice position it will generate a warning and use the latter. My main concern is there may be unintended consequences. The slice position is provided with low precision. While I estimate across all slices, there still may be variation between what is reported by slice thickness + slice gap. On the other hand, I am not sure the slice thickness + slice gap tags are reported with much precision either. Test this heavily close this issue if you are comfortable with this solution.

**Comment by baxpr** [comment] 2019-02-21 00:29
Sounds good to me - thanks for taking a look.

**Closed** 2019-02-21 00:29 UTC

**Comment by drmclem** [comment] 2019-02-21 11:40
Hi

Negative Slice gaps usually come about when the scan is collected with "Over Contiguous Slices" as an option. In this case the data for each slice comes from a region larger than the interslice distance and so they overlap in the slice direction leading to a negative gap. However this would not be consistent with the slice thickness reported above.

However I am not expecting a difference between the XML and PAR files in this case. So could @baxpr please email me separately and share the protocol/examcard and release and I'll look into it.

Matthew
