### ISSUE TITLE
dcm2niix cerate many nii by 1 DCM sequence

### ISSUE THREAD

**Issue by Bigsealion** [rordenlab/dcm2niix#468] opened 2020-12-25 12:19 UTC
I using dcm2niix which in MRIcroGL, and try to convert .dcm to .nii
However,  I get 10 .nii files, and each of them have part of the complete image. I can open this .dcm by 3dslicer or RadiAnt, but I want to convert .dcm to .nii by batch, so I need dcm2niix. 
I want to know how can I get a correct .nii file by dcm2niix? Thanks!
Following is printed information by dcm2niix.
`Compression will be faster with pigz.exe in the same folder as the executable
Chris Rorden's dcm2niiX version v1.0.20180622 (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 109 DICOM file(s)
Image Decompression is new: please validate conversions
slices not stacked: X-Ray Exposure varies (exposure 14, 15; number 1, 1). Use 'merge 2D slices' option to force stacking
Dims 512 512 22 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 1.25 2.5 3.75 5 6.25 7.5 8.75 10 11.25 12.5 13.75 97.5 98.75 100 101.25 102.5 103.75 105 106.25 107.5 108.75]
Warning: Missing images? Expected 22 images, but instance number (0020,0013) ranges from 1 to 88
instance=[ 1 2 3 4 5 6 7 8 9 10 11 12 79 80 81 82 83 84 85 86 87 88]
Convert 22 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1 (512x512x22x1)
slices not stacked: X-Ray Exposure varies (exposure 15, 16; number 1, 1). Use 'merge 2D slices' option to force stacking
Dims 512 512 31 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 1.25 2.5 3.75 5 6.25 7.5 8.75 10 11.25 12.5 13.75 15 60 61.25 62.5 63.75 65 66.25 67.5 68.75 70 71.25 72.5 73.75 75 76.25 77.5 78.75 80 81.25]
Warning: Missing images? Expected 31 images, but instance number (0020,0013) ranges from 13 to 78
instance=[ 13 14 15 16 17 18 19 20 21 22 23 24 25 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78]
Convert 31 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1a (512x512x31x1)
slices not stacked: X-Ray Exposure varies (exposure 16, 15; number 1, 1). Use 'merge 2D slices' option to force stacking
Convert 35 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1b (512x512x35x1)
slices not stacked: X-Ray Exposure varies (exposure 13, 12; number 1, 1). Use 'merge 2D slices' option to force stacking
Convert 6 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1c (512x512x6x1)
slices not stacked: X-Ray Exposure varies (exposure 12, 11; number 1, 1). Use 'merge 2D slices' option to force stacking
Convert 6 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1d (512x512x6x1)
slices not stacked: X-Ray Exposure varies (exposure 11, 10; number 1, 1). Use 'merge 2D slices' option to force stacking
Convert 6 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1e (512x512x6x1)
Convert 3 DICOM as I:\testdata\seg_test\XXXXX_1\20151013212002_1.25mm_stnd_3_e1f (512x512x3x1)
Conversion required 8.063000 seconds.
"D:\mricrogl_windows\mricrogl\dcm2niix" -b n -z y -f "%t_%p_%s" "I:\testdata\seg_test\XXXXX_1"
`

**Comment by neurolabusc** [comment] 2020-12-25 12:54
Please upgrade to the current release of MRIcroGL (v1.2.20201102) which will include the current stable release of [dcm2niix (v1.0.20201102)](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20201102). This will merge your CT scans despite the variations in Xray exposure. 

With MRIcroGL's graphical user interface, you can select how a series is merged despite variations. With MRIcroGL choose Import/ConvertDICOMtoNIfTI, in the new window you can choose the behavior from the pulldown menu with options being "Automatic Series Merging"  (default), "Always merge despite differences", and "Never merge with differences". From the command line you can use the `-m y` and `-m n` to control the merging behavior. 

You need to be aware that differences in X-Ray exposure may change your contrast across slices. Treating all these slices as identical may have unintended consequences. You may want to adapt your future data acquisitions to address this.

**Comment by Bigsealion** [comment] 2020-12-27 01:18
The new version dcm2niix in MRIcroGL can solve this problem!
Thank you very much!

**Comment by Bigsealion** [comment] 2020-12-27 08:11
In new version of dcm2niix, I got a new problem.
In most cases, it can create only 1 .nii.gz, but in some case, it will generate a corrected image, which will be set a suffix like ‘Tilt’ and ‘Eq’. After check, I think that 'Tile' is correction of degrees and 'Eq' iscorrection of interslice distance varies. Is my guess correct?
I found corrected images by 'Eq' with interpolated artifacts that I didn't want. so:
My Quescion: I want to know how to correct this image only by 'Tile' but not 'Eq'? Thanks!
Following is a typical example:
`D:\mricrogl_windows\mricrogl\Resources\dcm2niix.exe -f "%f_%p_%t_%s" -p y -z y -b n -o "I:\testdata\seg_test\op" "I:\testdata\seg_test\XXXXX_1"
Chris Rorden's dcm2niiX version v1.0.20201102  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900  (64-bit Windows)
Found 128 DICOM file(s)
Image Decompression is new: please validate conversions
Gantry Tilt based on 0018,1120 16.5, estimated from slice vector 16.5
Warning: Note these images have gantry tilt of 16.5 degrees (manufacturer ID = 2)
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Warning: Order specified by DICOM instance number is not spatial (reordering).
Convert 128 DICOM as I:\testdata\seg_test\op\XXXXX_1_1.1_Routine_Head_20130728000746_3a (512x512x128x1)
Gantry Tilt Correction is new: please validate conversions
Conversion required 15.534000 seconds.
`

**Comment by neurolabusc** [comment] 2020-12-27 12:08
Please see the [manual](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Computed_Tomography_.28CT.2C_CAT.29) for a description. The NIfTI format demands that all 2D slices in a 3D stack are equally spaced. The quaternion-based Q-form demands that the 3D volume is rectangular, not rhomboidal. 

If your acquisition does not meet these criteria, it can not be losslessly converted to NIfTI. This is not a limitation of my software, but a reflection of the NIfTI format (which was designed for MRI where gantry tilt and variable slice spacing is not used).

A feature of my software is it will attempt to interpolate a NIfTI volume from CT data when these assumptions are breached. This process is necessarily not lossless.

For future data collection, you may want to consider acquiring series with equidistant slice spacing and without gantry tilt. This will allow direct conversion to NIfTI without interpolation.

**Closed by neurolabusc** 2020-12-27 12:08 UTC
