### ISSUE TITLE
Sometimes "FrameTimesStart" missing from BIDS JSON format sidecar

### ISSUE THREAD

**Issue by Pedro-Filipe** [rordenlab/dcm2niix#781] opened 2024-01-30 19:48 UTC
Hi,

I am working with a bunch of single frame DICOMs containing diffusion weighted images. These series are repetitions of the same acquisition: 1 slice 7 images. (SIEMENS scanner)

When I convert these DICOMs to nifti, the sidecar json files of some series do not have the `FrameTimesStart` parameter, which I need to perform some b-value adustments. The series are all identical in terms of acquisition, so I am not sure why only some json files contain that parameter.

If I redo the conversion, the issue is reproducible, with the `FrameTimesStart` parameter missing for the same series numbers.

I am wondering if this is a known issue, or if there are any solutions. Unfortunately I cannot share the DICOM files at the moment.

Example output log for two series of DICOMs (I changed the real path with the word PATH in order not to have any sensitive info):

```bash

dcm2niix PATH_TO_DICOMS
Compression will be faster with 'pigz' installed http://macappstore.org/pigz/
Chris Rorden's dcm2niiX version v1.0.20240123  (JP2:OpenJPEG) (JP-LS:CharLS) Clang15.0.0 x86-64 (64-bit MacOS)
Found 14 DICOM file(s)
Warning: Discrepancy between reported (1.1s) and estimated (1.60042s) repetition time (issue 560).
Warning: All images appear to be a single slice - please check slice/vector orientation
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)
Convert 7 DICOM as PATH (96x256x1x7)
Warning: Discrepancy between reported (1.1s) and estimated (1.5575s) repetition time (issue 560).
Warning: Seconds between volumes varies
Warning: All images appear to be a single slice - please check slice/vector orientation
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)
Convert 7 DICOM as PATH (96x256x1x7)
Conversion required 0.090313 seconds (0.088417 for core code).

```

One of the series contains the parameter `FrameTimesStart` in the json sidecar file, but not the other.

This happens with both the homebrew installation and also the latest development commit:

```bash
❯ dcm2niix -version
Compression will be faster with 'pigz' installed http://macappstore.org/pigz/
Chris Rorden's dcm2niiX version v1.0.20240123  (JP2:OpenJPEG) (JP-LS:CharLS) Clang15.0.0 x86-64 (64-bit MacOS)
v1.0.20240123
```

Many thanks for any help.

**Comment by neurolabusc** [comment] 2024-01-30 20:35
@Pedro-Filipe see [issue 236](https://github.com/rordenlab/dcm2niix/issues/236) - I would strongly suggest exporting data from XA systems to enhanced rather than classic DICOM. The classic DICOMs used to be very impoverished, though this situation has improved a bit with more recent releases. Since the core images have changed so much over the years, I can not provide much more insight unless you [share sample images with my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by Pedro-Filipe** [comment] 2024-01-30 20:54
Many thanks for your reply. That is good to know. Unfortunately I have a lot of data in _classic DICOM_.

I will see if I can find some DICOMs with this issue that I can share with you.

**Comment by neurolabusc** [comment] 2024-01-30 21:01
@Pedro-Filipe I would encourage you to work with the Siemens Research Collaboration Manager associated with your center. They can help your team understand the problem. It sounds like these are issues with impoverished source images, not dcm2niix. Therefore, you will want to engage the manufacturer.

**Comment by Pedro-Filipe** [comment] 2024-01-31 14:55
Thank you for the support.

In case it is still worth it, I have sent you phantom scan DICOMs via your institutional email.

The same issue happens for this dataset. I can see in the individual DICOM headers the `AcquisitionTime`, which is what I assume is used to calculate the `FrameTimesStart` of the JSON file. But the field for some reason is not present.

**Comment by neurolabusc** [comment] 2024-01-31 16:17
I note that the dataset you sent me is from XA11. I worked closely with Siemens engineers to ensure sequence details were included with XA20 and later. XA10 and XA11 were very impoverished, and this limits the ability of any tool to work well. Some variations for exporting this data also added a huge amount of variability to the encoded times, which impacts the ability to extract timing parameters. These issues reflect limitations of the source data, and not dcm2niix. You should work with your Siemens Research Collaboration Manager for any unresolved questions. I am closing this issue as it is a duplicate of [issue 236](https://github.com/rordenlab/dcm2niix/issues/236). dcm2niix is limited by the quality of the images used.

**Closed** 2024-02-05 10:05 UTC
