### ISSUE TITLE
Inconsistent shuffling of individual Siemens standard B1 maps depending on slice orientation

### ISSUE THREAD

**Issue by gaspardcereza** [rordenlab/dcm2niix#527] opened 2021-07-07 21:03 UTC
Hi @neurolabusc and all the dcm2niix team ! I recently noticed a potential bug related to how uncombined B1 mapping dicom files are sorted in the converted nifti file.

## Some context

As part of the [shimming-toolbox](https://github.com/shimming-toolbox/shimming-toolbox) team, I am currently trying to add a B1 shimming feature to our toolbox. 

In order to compute the ideal shimming weights that will yield the best B1 homogeneity, I need individual B1 maps (maps of the B1 field distribution of each transmit element and for each slice). Such maps can be acquired using B1 mapping sequences (e.g. Siemens' `tfl2d1_16`).

## Bug description

After converting the dicoms obtained with the previously mentioned `tfl2d1_16` sequence into nifti files, I load them using `nibabel.load` in order to get my B1 maps and store them as a numpy array.

But I realized that the way the different maps are stored in the numpy array are not the same depending on the slice orientation.

The images below describe what happens with axial vs sagittal slices:

### **Axial slices** (9 slices / 8 coils)

*Iterating through the 4th dimension for the figures, and through the third dimension for the subplots:*

![image](https://user-images.githubusercontent.com/54723104/124823538-57913580-df3f-11eb-9221-10e755e667ec.png)

We notice here that all coils are stored in the correct order (from 1 to 8), but we have to concatenate the data along the 4th dimension in order to be able to correctly separate the slices.

### **Sagittal slices** (3 slices / 8 coils)

![image](https://user-images.githubusercontent.com/54723104/124827184-bbb5f880-df43-11eb-8328-ebc7c725ba8c.png)

Here we can see that, if slices are stored in the correct order along the 4th dimension, the coils are inverted along the 3rd.

Only magnitude maps are presented here, but the behaviour is the same for the phase.

I do not have any coronal data yet so I can't describe what would happen in that case.

<details><summary><b> Python code used to generate these figures </b></summary>

```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import nibabel as nib
import json
from tkinter import Tk
from tkinter.filedialog import askopenfilename

matplotlib.use('TkAgg')  # Allows for opening external windows to display plots (tested in PyCharm)

# Open a dialog box to select a .nii or a .gz file
root = Tk()
root.update()
fname_nifti = askopenfilename(title="Select the NIFTI file containing the B1 maps",
                              filetypes=[("NIFTI", "*.nii"), ("gzip compressed archive", "*.gz")])
root.destroy()  # Close dialog box after selecting file

image = np.asarray(nib.load(fname_nifti).dataobj)

# Get the json data
json_path = fname_nifti.split('.nii')[0] + '.json'
json_data = json.load(open(json_path))

# Magnitude values are stored in the first half of the 4th dimension
b1_mag = image[:, :, :, :image.shape[3] // 2] / 10  # Siemens magnitude values are stored in degrees x10

# Phase values are stored in the second half of the 4th dimension. Siemens phase range: [248 - 3848]
b1_phase = image[:, :, :, image.shape[3] // 2:]  # Scaling in interval [248 - 3848]
# Remove potential out of range zeros (set them as null phase = 2048)
b1_phase[b1_phase == 0] = 2048
# Scale the phase between [-pi, pi]
b1_phase = (b1_phase - 2048) * np.pi / 1800  # Scaling in range [-pi pi]

n_columns = np.ceil(np.sqrt(b1_mag.shape[2]))
if n_columns * np.floor(np.sqrt(b1_mag.shape[2])) >= b1_mag.shape[2]:
    n_rows = np.floor(np.sqrt(b1_mag.shape[2]))
else:
    n_rows = np.ceil(np.sqrt(b1_mag.shape[2]))

# Iterating along 3rd dimension
for i in range(b1_mag.shape[3]):
    plt.figure(figsize=[6.3, 6.5], tight_layout=dict(w_pad=0.1))
    # Iterating along 4th dimension
    for j in range(b1_mag.shape[2]):
        plt.subplot(n_rows, n_columns, j+1)
        plt.imshow(np.rot90(b1_mag[:, :, j, i]))
        plt.title(f'b1_magnitude[:,:,{j},{i}]')
        plt.axis('off')
plt.show()
```
</details>

## Reproduction steps

Steps to reproduce the behaviour:
1. Extract the files in [Issue_dcm2niix.zip](https://github.com/rordenlab/dcm2niix/files/6780042/Issue_dcm2niix.zip) (nifti/json/dicom files corresponding to the data presented above).
2. Use the Python code presented in the previous section (you should be asked to select a nifti file and the figures will then be plotted). 

You can also try to rerun dcm2niix on the provided dicoms. You should obtain the same nii and json files as the one provided here (with there original names). 

## Expected behaviour

I would expect the B1 maps to always be ordered in the same way, regardless of the slice orientation.

Ideally, the 3rd dimension of the array would correspond to the different slices and the 4th dimension would correspond to the different coils.

## Version

 - Chris Rorden's dcm2niiX version v1.0.20210317  Clang11.1.0 x86-64 (64-bit MacOS)

<details><summary><b>Troubleshooting</b></summary>
  
 - The latest stable release (20210317) does not solve the problem

 - Tried to install the latest commit on the development branch using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

But got the following error 
```zsh
(shim) gaspard@iMac console % g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp
nii_dicom.cpp:56:10: fatal error: 'openjpeg.h' file not found
#include "openjpeg.h"
         ^~~~~~~~~~~~
1 error generated.
```
</details>

I hope I gave enough context for you to understand the problem. Please let me know if you need anything else.

**Comment by KevinBerard** [comment] 2021-07-07 21:36
Typo in **Sagittal slices (3 slices / 8 coils)** : `Here we can se that, `
Other than that, it is clear enough.

**Comment by neurolabusc** [comment] 2021-07-07 23:52
This appears to be a limitation of these DICOM images, not dcm2niix. Neither the DICOM tags nor the CSA header differentiate the coils. One expects Siemens data to distinguish information from different coils with the private DICOM tag ([0051,100f](
https://github.com/rordenlab/dcm2niix/issues/187)), however in this sample dataset all images report the same string: `1H;1H;1H;1H;1H;1H;1H;1H;1H;1H;1H;1H;1H;1H;1H`.  It looks like this Siemens scanner is running a developmental operating system (E12U). I suggest working with your Siemens Research Collaboration Manager to have this information stored in future software releases. Without any distinguishing features to identify the coil, no tool will be able to automatically sort the data. 

It appears that Siemens use of Instance Number (0020,0013) is arbitrary for this dataset. Regardless, instance number is not a reliable feature for reading DICOM images as the standard does not require them to be sequential, meaningful or indeed even unique.

**Comment by jcohenadad** [comment] 2021-07-08 01:26
Thank you for looking into this and for your insightful comments as always @neurolabusc !
Indeed, it looks like the problem has to be fixed at the source (ie: Dicom). We will explore further on the Siemens side. 

Regardless this inconsistency, does `dcm2niix` support Dicom series with uncombined Tx elements (for B1+ maps)? I understand from this related issue https://github.com/rordenlab/dcm2niix/issues/187 that Rx elements (when "save uncombined" is checked) are identified by the field (0051,100f), but I would expect that Tx elements would be identified elsewhere.

**Comment by gaspardcereza** [comment] 2021-07-08 14:19
Thank you for the insights @neurolabusc ! 

Regarding your answer, another question comes to my mind: 

When I visualise the DICOM files obtained with `tfl2d1_16` (Siemens' standard B1 mapping sequence) in a DICOM viewer (I tried with `RadiAnt` and `Horos`), the images are presented in the correct order (from coil 1 to 8). 

Could this be simply due to the fact that this coincides with the alphabetic sorting of the DICOM files in their folder, or does that mean that these softwares use another DICOM tag that carries the information about the coil number (e.g. `Instance Number` in that case) ?

**Comment by neurolabusc** [comment] 2021-07-09 12:15
@gaspardcereza the issue is that the NIfTI format demands that the first three dimensions be spatial. Where XYZ are the spatial dimensions and C is the Coil number, the instance number order would be XYCZ. In other words, the problem is resolved once dcm2niix is provided with some mechanism to distinguish the coils from each other. In general, dcm2niix disregards [instance number (0020,0013)](https://dicom.innolitics.com/ciods/ct-image/general-image/00200013) as it is unreliable. For example, Siemens reuses instance numbers across echoes for its product gradient echo field maps. Long story short, the input images are under specified. Once they provide distinguishing features dcm2niix will work as expected.

**Comment by gaspardcereza** [comment] 2021-07-09 13:41
Thank you for this precisions @neurolabusc. For now I will try to work with a "temporary solution" that reorders the B1 maps after loading the NIfTI. In the end, I hope Siemens will address the problem but this will probably take a while... Thanks again for the help !

**Comment by neurolabusc** [comment] 2021-07-09 13:55
Closing issue, please open a new issue once there is a way to identify channels.

**Closed** 2021-07-09 13:56 UTC
