### ISSUE TITLE
Philips DCE-MRI DICOM 

### ISSUE THREAD

**Issue by neurosc** [rordenlab/dcm2niix#463] opened 2020-12-11 12:45 UTC
Hi,

I would like to report an issue about the conversion of DCE-MRI enhanced dicom data (multiple acquired volumes over time) to nifti with the latest version of dcm2niix. This scan was acquired at a Philips scanner.  Instead of providing one 4D nifti as output (x,y,z,60 timepoints), it gives two 4D niftis: 1)  4D nifti with 27 volumes over time and 2) 4D nifti with 33 volumes over time. The files seem to be randomly divided over these 2 niftis and are not sorted. 
However, I noticed that this conversion goes well for an older version of dcm2niix (e.g. 2018).

**Comment by neurolabusc** [comment] 2020-12-11 13:01
Does the software warn you why the `Slices not stacked`. For example, [`Slices not stacked: coil varies`](https://neurostars.org/t/dcm2niix-splitting-a-scan-run-into-multiple-files/17659/5). A feature of recent releases of dcm2niix is that it is able to detect corrupted or damaged DICOM datasets. The warnings should alert you to situations that need human intervention.

**Comment by neurolabusc** [comment] 2020-12-12 13:24
Does forcing images to be merged `-m y` regardless of echo time, exposure time, etc. resolve your issue? 
```
dcm2niix -m y -f %s_%p /path/to/DICOMs
```
If this stacks all your images, you may want to determine if the reasons they were not combined impacts your subsequent analyses. For example, if running the command
```
dcm2niix -m n -f %s_%p /path/to/DICOMs
```
Reports `Slices not stacked: echo varies (TE 3.6, 4.7; echo 1, 2)` you may choose to ignore this variation, or you may want to model this in your analysis.

**Comment by neurosc** [comment] 2020-12-14 07:50
Hi,Unfortunetely, this doesn't solve the issue and gives the same output as earlier. -------- Oorspronkelijk bericht --------Onderwerp: Re: [rordenlab/dcm2niix] Philips DCE-MRI DICOM  (#463)Van: Chris Rorden Aan: rordenlab/dcm2niix Cc: neurosc ,Author 
Does forcing images to be merged -m y regardless of echo time, exposure time, etc. resolve your issue?
dcm2niix -m y -f %s_%p /path/to/DICOMs

If this stacks all your images, you may want to determine if the reasons they were not combined impacts your subsequent analyses. For example, if running the command
dcm2niix -m n -f %s_%p /path/to/DICOMs

Reports Slices not stacked: echo varies (TE 3.6, 4.7; echo 1, 2) you may choose to ignore this variation, or you may want to model this in your analysis.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-743755821",
"url": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-743755821",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neurosc** [comment] 2020-12-14 07:52
No, it doesn't give a reason why they are not stacked and randomly shuffled. The following is printed:Philips Scaling Values RS:RI:SS = 2.15067:0:0.000823664 (see PMC3998685)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/DICOM_WIP_3D_T1_DCE_FAST_20201203141930_901 (256x256x21x33)no Varies1.53455 -3142 651.74Using RWVSlope:RWVIntercept = 1.53455:-3142 Philips Scaling Values RS:RI:SS = 1.53455:-3142:651.74 (see PMC3998685)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/DICOM_WIP_3D_T1_DCE_FAST_20201203141930_901_ph (256x256x21x30)no Varies1.53455 -3142 651.74Using RWVSlope:RWVIntercept = 1.53455:-3142 Philips Scaling Values RS:RI:SS = 1.53455:-3142:651.74 (see PMC3998685)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/DICOM_WIP_3D_T1_DCE_FAST_20201203141930_901_pha (256x256x21x30)no Varies2.15067 0 0.000823664Using RWVSlope:RWVIntercept = 2.15067:0 Philips Scaling Values RS:RI:SS = 2.15067:0:0.000823664 (see PMC3998685)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/DICOM_WIP_3D_T1_DCE_FAST_20201203141930_901a (256x256x21x27)no Varies-------- Oorspronkelijk bericht --------Onderwerp: Re: [rordenlab/dcm2niix] Philips DCE-MRI DICOM  (#463)Van: Chris Rorden Aan: rordenlab/dcm2niix Cc: neurosc ,Author 
Does the software warn you why the Slices not stacked. For example, Slices not stacked: coil varies. A feature of recent releases of dcm2niix is that it is able to detect corrupted or damaged DICOM datasets. The warnings should alert you to situations that need human intervention.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-743179970",
"url": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-743179970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neurolabusc** [comment] 2020-12-14 14:43
Is it possible that these images do not share a series or study instance UID? You can check by putting %j in the filename argument:
 -  %j=series instance UID (from 0020,000E)
 - %k=study instance UID (from 0020,000D)

for example
```
dcm2niix -f %t_%s_%j_%k /path/to/DICOMs
```
Feel free to send me a link to these images via Box/GoogleDrive veto the email listed in my avatar.

**Comment by neurosc** [comment] 2020-12-16 09:54
I checked the series and study instance UID and these are exactly the same for all DCE images.  Unfortunetely, I have no permission to share the images.-------- Oorspronkelijk bericht --------Onderwerp: Re: [rordenlab/dcm2niix] Philips DCE-MRI DICOM  (#463)Van: Chris Rorden Aan: rordenlab/dcm2niix Cc: neurosc ,Author 
Is it possible that these images do not share a series or study instance UID? You can check by putting %j in the filename argument:

%j=series instance UID (from 0020,000E)
%k=study instance UID (from 0020,000D)

for example
dcm2niix -f %t_%s_%j_%k /path/to/DICOMs

Feel free to send me a link to these images via Box/GoogleDrive veto the email listed in my avatar.

**Comment by neurolabusc** [comment] 2020-12-16 10:44
Can you test the latest commit to the development branch (it will report v1.0.20201216). It can provide more details regarding why slices from a single series are not combined, and also provides additional overrides for these options.  

If you can provide the output from this command, it should provide richer details regarding why series 901 has been split:
```
dcm2niix -v 1 -f %t_%s_%j_%k /path/to/DICOMs
```

The merge `o`verride option will combine scans despite many variations (such as [changes in the coil](https://neurostars.org/t/dcm2niix-splitting-a-scan-run-into-multiple-files/17659/5)).
```
dcm2niix -m o -f %t_%s_%j_%k /path/to/DICOMs
```

@drmclem I realize this is a WIP (Work-In-Progress) not a product sequence, so you may not have any details. However, can you think of any reasons different slices in this sequence may vary from each other (coil, UIDS, protocol name, series time, etc)?

**Comment by neurosc** [comment] 2020-12-16 19:42
The problem with the merge option is that it merges the phase images with the magnitude images in a spatial dimension instead of a fifth dimension. This is the output of your suggestion (it gives a warning about the TR here) :DICOM file: /home/g10041175/CRUCM001_B_enhancedDICOM/DICOM/IM_0019 patient position (0020,0032)	48.0578	-142.83	122.788 patient position end (0020,0032)	-31.8813	-145.306	124.687 orient (0020,0037)	-0.0312816	0.999416	-0.0137208	-0.023292	-0.0144527	-0.999624 acq 9 img 1 ser 901 dim 256x256x21x120 mm 1x1x4 offset 5512756 loc 21 valid 1 ph 1 mag 1 nDTI 120 3d 1 bits 16 littleEndian 1 echo 1 coilCRC 654392638 TE 2.493 TR 5.3Warning: Assuming TR = 732.219ms, not 0018,0080 = 5.3ms (see issue 369)Parameters vary across 3D volumes packed in single DICOM file: 0 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 1 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 2 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 3 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 4 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 5 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 6 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 7 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 8 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 9 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 10 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 11 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 12 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 13 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 14 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 15 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 16 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 17 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 18 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 19 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 20 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 21 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 22 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 23 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 24 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 25 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 26 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 27 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 28 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 29 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 30 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 31 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 32 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 33 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 34 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 35 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 36 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 37 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 38 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 39 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 40 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 41 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 42 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 43 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 44 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 45 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 46 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 47 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 48 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 49 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 50 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 51 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 52 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 53 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 54 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 55 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 56 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 57 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 58 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 59 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 60 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 61 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 62 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 63 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 64 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 65 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 66 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 67 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 68 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 69 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 70 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 71 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 72 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 73 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 74 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 75 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 76 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 77 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 78 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 79 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 80 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 81 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 82 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 83 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 84 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 85 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 86 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 87 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 88 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 89 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 90 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 91 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 92 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 93 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 94 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 95 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 96 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 97 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 98 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 99 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 100 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 101 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 102 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 103 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=1 104 TE=2.493 Slope=2.15067 Inter=0 PhilipsScale=0.000823664 Phase=0 105 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 106 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 107 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 108 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 109 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 110 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 111 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 112 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 113 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 114 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 115 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 116 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 117 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1 118 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=0 119 TE=2.493 Slope=1.53455 Inter=-3142 PhilipsScale=651.74 Phase=1no Varies2.15067 0 0.000823664Converting /home/g10041175/CRUCM001_B_enhancedDICOM/DICOM/IM_0019Using RWVSlope:RWVIntercept = 2.15067:0 Philips Scaling Values RS:RI:SS = 2.15067:0:0.000823664 (see PMC3998685)Potential Alternative Intensity Scalings R = raw value, P = precise value, D = displayed value RS = rescale slope, RI = rescale intercept,  SS = scale slope D = R * RS + RI    , P = D/(RS * SS)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/20201203141930_WIP_3D_T1_DCE_FAST_901_1.3.46.670589.11.78053.5.0.12876.2020120315375746968_1.2.752.24.5.6.20201124021459.6626410 (256x256x21x33)no Varies1.53455 -3142 651.74Converting /home/g10041175/CRUCM001_B_enhancedDICOM/DICOM/IM_0019Using RWVSlope:RWVIntercept = 1.53455:-3142 Philips Scaling Values RS:RI:SS = 1.53455:-3142:651.74 (see PMC3998685)Potential Alternative Intensity Scalings R = raw value, P = precise value, D = displayed value RS = rescale slope, RI = rescale intercept,  SS = scale slope D = R * RS + RI    , P = D/(RS * SS)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/20201203141930_WIP_3D_T1_DCE_FAST_901_1.3.46.670589.11.78053.5.0.12876.2020120315375746968_1.2.752.24.5.6.20201124021459.6626410_ph (256x256x21x30)no Varies1.53455 -3142 651.74Converting /home/g10041175/CRUCM001_B_enhancedDICOM/DICOM/IM_0019Using RWVSlope:RWVIntercept = 1.53455:-3142 Philips Scaling Values RS:RI:SS = 1.53455:-3142:651.74 (see PMC3998685)Potential Alternative Intensity Scalings R = raw value, P = precise value, D = displayed value RS = rescale slope, RI = rescale intercept,  SS = scale slope D = R * RS + RI    , P = D/(RS * SS)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/20201203141930_WIP_3D_T1_DCE_FAST_901_1.3.46.670589.11.78053.5.0.12876.2020120315375746968_1.2.752.24.5.6.20201124021459.6626410_pha (256x256x21x30)no Varies2.15067 0 0.000823664Converting /home/g10041175/CRUCM001_B_enhancedDICOM/DICOM/IM_0019Using RWVSlope:RWVIntercept = 2.15067:0 Philips Scaling Values RS:RI:SS = 2.15067:0:0.000823664 (see PMC3998685)Potential Alternative Intensity Scalings R = raw value, P = precise value, D = displayed value RS = rescale slope, RI = rescale intercept,  SS = scale slope D = R * RS + RI    , P = D/(RS * SS)Convert 1 DICOM as /home/g10041175/CRUCM001_B_enhancedDICOM/nifti1/20201203141930_WIP_3D_T1_DCE_FAST_901_1.3.46.670589.11.78053.5.0.12876.2020120315375746968_1.2.752.24.5.6.20201124021459.6626410a (256x256x21x27)-------- Oorspronkelijk bericht --------Onderwerp: Re: [rordenlab/dcm2niix] Philips DCE-MRI DICOM  (#463)Van: Chris Rorden Aan: rordenlab/dcm2niix Cc: neurosc ,Author 
Can you test the latest commit to the development branch (it will report v1.0.20201216). It can provide more details regarding why slices from a single series are not combined, and also provides additional overrides for these options.
If you can provide the output from this command, it should provide richer details regarding why series 901 has been split:
dcm2niix -v 1 -f %t_%s_%j_%k /path/to/DICOMs

The merge override option will combine scans despite many variations (such as changes in the coil).
dcm2niix -m o -f %t_%s_%j_%k /path/to/DICOMs

@drmclem I realize this is a WIP (Work-In-Progress) not a product sequence, so you may not have any details. However, can you think of any reasons different slices in this sequence may vary from each other (coil, UIDS, protocol name, series time, etc)?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-746078224",
"url": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-746078224",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neurolabusc** [comment] 2020-12-16 21:00
1. Are you sure you are running the latest commit (v1.0.20201216)?  The text you pasted does not include the first few lines of output that report the version, and the formatting is lost, making it hard to understand what is going on. Can I suggest you redirect the entire output to a text file and then drag-and-drop the entire text file onto your GitHub response:
```
dcm2niix -v 1 -f %t_%s_%j_%k /path/to/DICOMs > out.txt
```

**Comment by neurosc** [comment] 2020-12-17 07:37
I'm running v1.0.20200331, so a recent version, but not the latest one. -------- Oorspronkelijk bericht --------Onderwerp: Re: [rordenlab/dcm2niix] Philips DCE-MRI DICOM  (#463)Van: Chris Rorden Aan: rordenlab/dcm2niix Cc: neurosc ,Author 

Are you sure you are running the latest commit (v1.0.20201216)?  The text you pasted does not include the first few lines of output that report the version, and the formatting is lost, making it hard to understand what is going on. Can I suggest you redirect the entire output to a text file and then drag-and-drop the entire text file onto your GitHub response:

dcm2niix -v 1 -f %t_%s_%j_%k /path/to/DICOMs > out.txt


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-747008401",
"url": "https://github.com/rordenlab/dcm2niix/issues/463#issuecomment-747008401",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neurolabusc** [comment] 2020-12-17 12:03
So the latest stable release ([v1.0.20201102](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20201102)) resolves your issue?

**Comment by neurosc** [comment] 2020-12-18 11:55
No, I still have the same problem with the latest version. I have attached the output in a txt file

[out.txt](https://github.com/rordenlab/dcm2niix/files/5715462/out.txt)

**Comment by neurolabusc** [comment] 2020-12-18 12:02
What is the output from the developmental commit (v1.0.20201216)?

**Comment by neurosc** [comment] 2020-12-18 14:18
Where can I download this developmental commit?

**Comment by neurolabusc** [comment] 2020-12-18 17:02
(if neither of these options work, email me at address in my avatar and I can send you a recompiled copy):

Unix users can test the latest developmental commit:
```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

Windows users should be able to get a compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).

**Comment by neurosc** [comment] 2020-12-18 17:24
Thank you! 
Unfortunately, this version doesn't solve the problem. I have attached the output text.

[out1216.txt](https://github.com/rordenlab/dcm2niix/files/5717125/out1216.txt)

**Comment by neurolabusc** [comment] 2020-12-18 19:13
I do not have sufficient information to resolve this problem. I do not have access to an exemplar. This data is from a WIP (work in progress) sequence rather than a product sequence. Without seeing an example, it is unclear if the issue is with dcm2niix or the DICOM, and whether dealing with this will cause unintended consequences as seen with previous [single customer solutions](https://github.com/rordenlab/dcm2niix/issues/395). Since this is a WIP, you will have access to a Philips Research Collaboration manager. I would work with them to resolve this. I would discourage you from using this nascent sequence with any version of my software, even if it appears to work on older versions. Philips research customers also have access to the Philips proprietary NIfTI export and PAR/REC export. This may be a better choice for this data. Feel free to submit a pull request if you have a solution you wish to share with the rest of the community.

**Closed by neurolabusc** 2020-12-18 19:13 UTC
Labels: wontfix
