### ISSUE TITLE
Problem with file read in nii_dicom.cpp

### ISSUE THREAD

**Issue by seandoyle** [rordenlab/dcm2niix#107] opened 2017-06-20 02:13 UTC
Hi -

There was a recent checkin for improving the I/O performance - but an error is thrown if the size of the file is below 1MB. When I read a standard CT slice the read fails. Here's the code from line 2528:
```
if (sz < MaxBufferSz) {
         printError("Only loaded %zu of %zu bytes for %s\n", sz, MaxBufferSz, fname);
         fclose(file);
         return d;
    }
```
This results in the following error message on the console: 
```
Error: Only loaded 530540 of 1000000 bytes for ..
```
Shouldn't the inequality be reversed? 

Thanks

Sean

**Comment by neurolabusc** [comment] 2017-06-20 13:08
Mea culpa, as you noted this regression was caused by my acceleration in converting very large files. Fixed in latest commit.

**Closed by neurolabusc** 2017-06-20 13:08 UTC
