### ISSUE TITLE
bvec/bval not generated 

### ISSUE THREAD

**Issue by vblsu** [rordenlab/dcm2niix#402] opened 2020-06-04 15:47 UTC
Dear Chris,
I had tried to convert my DTI DICOM data from Philips MRI to NIfTI but it is showing
Warning: No bvec/bval files created: only single value after ADC excluded when used MRIcro for conversion.
The following was the message when I used MRIcron
Found 1768 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Using RWVSlope:RWVIntercept = 1.38608:0
Philips Scaling Values RS:RI:SS = 1.38608:0:0 (see PMC3998685)
Convert 1768 DICOM as /Users/vinita/Desktop/DTItest (144x144x52x34)
Conversion required 1.995563 seconds (0.931139 for core code).

I have tried MRIcro, MRIconvert and MRIcron without success.

I would really appreciate your help.

Thanks !

VB

**Comment by vblsu** [comment] 2020-06-04 15:47
Hello Chris,

I have sent my DTI dcm files on your avatar email via dropbox and also attached the equipment details image here.

Please let me know if you have any further questions.

Thank you for your help !

VB

**Comment by vblsu** [comment] 2020-06-04 15:48
![IMG_5340](https://user-images.githubusercontent.com/65729223/83778851-da670300-a650-11ea-93b9-b6374e67d529.JPG)
![IMG_5341](https://user-images.githubusercontent.com/65729223/83778854-dc30c680-a650-11ea-95e9-4380f3af677c.JPG)

Please find attached images about our equipment. I would appreciate your help to resolve this matter

**Comment by drmclem** [comment] 2020-06-04 15:52
Should be a B0 from that scan - how was it exported ?

**Comment by vblsu** [comment] 2020-06-04 16:02
Uploaded into Horos and the exported from Horos. Then converted to nii with MRICro

**Comment by drmclem** [comment] 2020-06-04 16:04
My suspicion is therefore your problem is with Horos - can you try exporting directly from the scanner (use Diskfile from patient administration and Enhanced format) and then convert.

**Comment by neurolabusc** [comment] 2020-06-04 16:21
@vblsu thank you for sharing the images with me. The issue is clearly with your images, not my software. To demonstrate this, take a image where visual inspection clearly shows that a diffusion gradient has been applied and run dcmdump (or gdcmdump) to inspect the header. Look at the tags used by [Philips](https://github.com/rordenlab/dcm2niix/tree/master/Philips) to encode the [bvec/bval](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_Philips) information. Note that the provided values are not plausible:

```
(0018,9087) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValue
(0018,9089) FD 0\0\0                                    #  24, 3 DiffusionGradientOrientation
```

Typically, a scan with a large DiffusionBValue and zero DiffusionGradientOrientation refers to a derived image (e.g. TRACE), but visual inspection reveals that is not the case. Further, the magnitude of the DiffusionBValue is clearly incorrect (the console reports a max b factor of 800 and evener extreme DKI scans values around 2500 seem to be the maximum).

Also note how many other [FD](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html) tags have the same implausible value:

```
(0018,9019) FD 7.229999999999997e+75                    #   8, 1 TagAngleFirstAxis
(0018,9030) FD 7.229999999999997e+75                    #   8, 1 TagSpacingFirstDimension
(0018,9602) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXX
(0018,9603) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXY
(0018,9604) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueXZ
(0018,9605) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueYY
(0018,9606) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueYZ
(0018,9607) FD 7.229999999999997e+75                    #   8, 1 DiffusionBValueZZ
(0020,9256) FD 7.229999999999997e+75                    #   8, 1 RespiratoryTriggerDelayThreshold
```

As @drmclem suggestions, I would look at the provenance of the images. I suspect that if you get the images direct from your scanner they will be intact, and some tool that touched these images corrupted some of the crucial meta data.

**Comment by vblsu** [comment] 2020-06-04 19:48
Hello,
Thank you drmclem and Chris for your prompt reply. I will try the above suggestion and let you know how it goes soon.

VB

**Comment by vblsu** [comment] 2020-06-05 18:38
Hello,
Quick question will sending the raw files from a CD to Sectra-PACS alter the header ?
We usually have our patient data on a CD which is stored in a propreitary format and we put it in Horos to decipher the files for further use.

**Comment by neurolabusc** [comment] 2020-06-05 19:12
Yes, the PACS system should alter the DICOM header. For example, my copy of the terrific [dcmtk](https://dicom.offis.de/dcmtk.php.en) brands every DICOM file it touches:
``` 
(0002,0013) SH [OFFIS_DCMTK_354]                        #  16, 1 ImplementationVersionName
```


However, one hopes that the PACS system will not corrupt the header. While most systems are well-behaved, the DICOM standard is complex. There are certainly examples where transferring DICOM images has had unintended consequences. For example, the system might decide to use a compressed transfer syntax. While the DICOM standard allows this, the DICOM standard also only requires valid tools to support the uncompressed syntax. 

A famous example of a PACS system disrupting DICOM images is the GE [GEIIS](https://forum.dcmtk.org/viewtopic.php?t=2016) which would insert a thumbnail image that violated the DICOM standard. 

More recently, vendors introduced "enhanced DICOM" that has useful new features. This format is not compatible with many older tools and can cause issues with tools that are not enhanced aware. 

Likewise, due to the complexity there are several cases where vendors implemented DICOM in unintuitive or incorrect ways that could be amplified when they were touched by a PACS system. The most famous example is from ancient GE systems that would report that DICOM elements with 10 bytes had a length of 13. Fortunately, this is easy to detect as all DICOM elements must have an even length. This explains a bizarre kludge found in many DICOM readers (e.g. [ImageJ](https://imagej.nih.gov/ij/source/ij/plugin/DICOM.java)):
```
if (elementLength==13 && !oddLocations) elementLength = 10; 
```

**Closed** 2020-06-08 13:20 UTC
