### ISSUE TITLE
GE multi-shell dwi scans get incorrectly split

### ISSUE THREAD

**Issue by josephmje** [rordenlab/dcm2niix#247] opened 2018-11-28 15:39 UTC
Hi,

I have multishell dwi data acquired on a GE Discovery MR750 scanner. I've noticed a difference in the dicom to nifti reconstruction between v20180622 and v201610101. The older version outputs a nifti with 35 timepoints. However, the newer version incorrectly splits the nifti into 2 files: one with 32 timepoints and an ADC image.

**Comment by neurolabusc** [comment] 2018-11-28 17:20
Please try the latest [release (v1.0.20181125)](https://github.com/rordenlab/dcm2niix/releases). I suspect this is a duplicate of [issue 245](https://github.com/rordenlab/dcm2niix/issues/245) where users created B=0 images in custom gradient files using nomenclature typically reserved for trace images. The latest release introduces a kludge for this, but this should be fixed at the source: users and GE need to coordinate to avoid these conflicts.

**Closed** 2018-11-29 23:49 UTC
