### ISSUE TITLE
Phase encoding direction

### ISSUE THREAD

**Issue by syunchoi** [rordenlab/dcm2niix#652] opened 2022-11-22 08:22 UTC
Hi,

I am using the dcm2niix command to convert dwi dcm to nifti file, and I'm having trouble with phase encoding direction.
I'm sure my data is L->R direction because I set the phase encoding parameter as L->R. However, when I use dcm2niix and check json file, the phase encoding direction is in 'j', which makes me confused because I think 'j' indicates 'AP' and not 'LR'.
Below is some fo the information of dicom image header. Also, MSMA is in S(R>>L)-C(A>>P)-T(F>>H).   
It would be great if anyone could help me with this issue.

Thank you

(0018, 0020) Scanning Sequence                   CS: 'EP'

(0018, 0025) Angio Flag                          CS: 'N'
(0018, 0050) Slice Thickness                     DS: '2.2999999523163'
(0018, 0080) Repetition Time                     DS: '3200.0'
(0018, 0081) Echo Time                           DS: '110.0'
(0018, 0083) Number of Averages                  DS: '1.0'
(0018, 0084) Imaging Frequency                   DS: '123.177387'
(0018, 0085) Imaged Nucleus                      SH: '1H'
(0018, 0086) Echo Number(s)                      IS: '1'
(0018, 0087) Magnetic Field Strength             DS: '3.0'
(0018, 0088) Spacing Between Slices              DS: '2.299999961907'
(0018, 0089) Number of Phase Encoding Steps      IS: '83'
(0018, 0091) Echo Train Length                   IS: '1'
(0018, 0093) Percent Sampling                    DS: '100.0'
(0018, 0094) Percent Phase Field of View         DS: '100.0'
(0018, 0095) Pixel Bandwidth                     DS: '1299.0'
(0018, 1000) Device Serial Number                LO: '35422'
(0018, 1020) Software Versions                   LO: 'syngo MR B19'
(0018, 1030) Protocol Name                       LO: 'DTI_BLIP_LR'
(0018, 1251) Transmit Coil Name                  SH: 'Body'
(0018, 1310) Acquisition Matrix                  US: [110, 0, 0, 110]
(0018, 1312) In-plane Phase Encoding Direction   CS: 'COL'
(0018, 1314) Flip Angle                          DS: '90.0'
(0018, 1315) Variable Flip Angle Flag            CS: 'N'
(0018, 1316) SAR                                 DS: '0.20510281195378'
(0018, 1318) dB/dt                               DS: '0.0'
(0018, 5100) Patient Position                    CS: 'HFS'

(0051, 100b) [AcquisitionMatrixText]             LO: '110p*110'
(0051, 100c) [Unknown]                           LO: 'FoV 2303*2303'
(0051, 100e) [Unknown]                           LO: 'Tra>Cor(-8.2)>Sag(-1.9)'

**Comment by neurolabusc** [comment] 2022-11-22 12:44
Feel free to share your images [with my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). For Siemens V* EPI axial acquisitions saved as mosaics we typically expect 0018,1312 to be [`COL` for A>>P and P>>A](https://github.com/neurolabusc/dcm_qa/blob/master/Ref/noPF_noPAT_noPOS_PEres100_ES0p59_BW2222_AP_8.json) while [ [`ROW` for L>>R and R>>L](https://github.com/neurolabusc/dcm_qa/blob/master/Ref/noPF_noPAT_noPOS_PEres100_ES0p60_BW2222_LR_31.json). There was a long-standing bug with Siemens consoles that using `Copy References` would cause a 90-degree flip on phase encoding polarities where a 180 degree reversal was specified. You may want to contact your sites Siemens Research Collaboration Manager for more insight.

**Comment by neurolabusc** [comment] 2022-11-25 23:18
Closing: dcm2niix handles validation datasets correctly. Without seeing an example dataset, it is unclear if the root cause for this issue.

**Closed by neurolabusc** 2022-11-25 23:18 UTC
