### ISSUE TITLE
Splitting 3D DICOM sets in 2 and the resulting file only contains the 1st half. 

### ISSUE THREAD

**Issue by raphaelcalmon** [rordenlab/dcm2niix#355] opened 2019-11-13 14:40 UTC
I apologise if this issue is not supposed to be address hire. 
When converting 3D DICOM image sets using the newest version, the resulting nifti file contains only half of the DICOM images:
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
Found 252 DICOM file(s)
Convert 252 DICOM as ./Ax_T1_BRAVO.20191112092343 (512x512x126x2)

Where the previous version would include all images: 
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
Found 252 DICOM file(s)
Convert 252 DICOM as ./Ax_T1_BRAVO.20191112092343 (512x512x252x1)

**Comment by neurolabusc** [comment] 2019-11-13 15:05
I believe this is a duplicate of [the recent comments regarding issue 306](https://github.com/rordenlab/dcm2niix/issues/306). Specifically, we need to handle number of locations differently for 4D EPI volumes as for 3D volumes where interpolation is applied between slices. As I noted there, for future acquisitions I would advise you to turn off interpolation. However, the latest development build (v1.0.20191111) should resolve your issue. If you have a Windows computer, you can get a compiled version by clicking on the AppVeyor link from the development branch's home page (the executable is an 'Artifact'). If you have a Unix system, you can build as:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

**Comment by neurolabusc** [comment] 2019-11-13 15:59
For future reference, see [issue 209](https://github.com/rordenlab/dcm2niix/issues/209) and [issue 306](https://github.com/rordenlab/dcm2niix/issues/306) for examples where these tags must be given different precedence. The current development build should resolve both issues.

**Closed** 2019-11-16 13:08 UTC
