### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by RJMullins** [rordenlab/dcm2niix#378] opened 2020-02-26 20:47 UTC
I've noticed that the newer dcm2niix does not process multiple folders anymore - the error says "recompile with myEnableMultipleInputs" and only processes the last one. This has caused many problems with my prior processing streams and I am wondering if there is a downloadable version that has the old behavior?

**Comment by neurolabusc** [comment] 2020-02-27 17:54
@RJMullins please see [issue 123](https://github.com/rordenlab/dcm2niix/issues/123). The issue is that shell filename expansion. Specifically, some shells intercept commands between the command line and the executable.

Therefore, for modern versions of dcm2niix, if you want to convert the folders `~/DCM/A` and `~/DCM/B` you could either run 
```
 dcm2niix ~/DCM/A
 dcm2niix ~/DCM/B
```
or
```
 dcm2niix ~/DCM
```
but you can **not** run
```
 dcm2niix ~/DCM/A  ~/DCM/B
```

I would suggest you update your scripts to generate one instance of dcm2niix per folder. Indeed, if you do this [asynchronously](https://github.com/neurolabusc/dcm2niiXL) you can convert files in parallel which is typically faster (though parallel conversion requires having sufficient CPU threads and can be impacted by disk contention).

If you must have this feature, you could recompile dcm2niix with the `myEnableMultipleInputs` directive:
```
g++ -O3 -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG -DmyEnableMultipleInputs
```

I would discourage this, as your scripts will depend on a atypical compilation and the resulting executable would be sensitive to shell filename expansion. I am very reluctant to introduce changes in my tools that break compatibility. When compatibility breaking changes to the interface are made this typically reflects that the previous implementation had unintended consequences that could not be addressed in any other way.

**Closed** 2020-03-03 14:54 UTC
