### ISSUE TITLE
4d Isotropic DWI Siemens Verio split into 2d slices

### ISSUE THREAD

**Issue by dagra** [rordenlab/dcm2niix#409] opened 2020-07-14 13:11 UTC
Hi,

I have an Isotropic DWI from Siemens Verio which dcm2niix converts into multiple niis of shape `(64, 64, 1, 1)` instead of a single 4d. I tried to identify the problem, but I haven't found it yet. I tried [xiangruili's dicm2nii](https://github.com/xiangruili/dicm2nii) and it seems to convert it successfully along with the bval/bvec files and the final shape is `(104, 86, 26, 2)`.

I send you in private via email the dataset.

Thanks!

**Comment by neurolabusc** [comment] 2020-07-14 14:14
This is a [duplicate of issue 395](https://github.com/rordenlab/dcm2niix/issues/395)

dcm2niix is working correctly. Each volume reports a unique [trigger time](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) and therefore is segmented based on the recipe provided by the DICOM images. If you want to ignore this information, run dcm2niix with the `-m y` argument to merge these files. See [these examples](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI) for situations where trigger time is an important parameter. Essentially, this is a situation where different users have different expectations regarding whether they want the data to be segmented or not. 

In my limited experience, Philips BOLD fMRI does not typically report trigger time (0018,1060) for each TR (where most users would want to stack data into a 4D series), however I have seen it used for physiological gating (where one does want to segment based on this information). Maybe people more familiar with Philips DICOM (@drmclem, @baxpr) can provide guidance for how to robustly determine whether data should be based on trigger time. One idea is that for Philips data we could ignore TriggerTime if HeartRate is zero, but I am not sure this would work for all situations (e.g. repiratory rather than heart rate gating).

```
(0018,1020) LO [5.3.1\5.3.1.2]                          #  14, 2 SoftwareVersions
(0018,1030) LO [task-rest_bold]                         #  14, 1 ProtocolName
(0018,1060) DS [444399.99]                              #  10, 1 TriggerTime
(0018,1088) IS [0]                                      #   2, 1 HeartRate
```

**Comment by neurolabusc** [comment] 2020-07-14 16:02
This is a creative use of the IconImageSequence (0088,0200). This implementation looks legal, but this commit may have unintended consequences for DICOM images corrupted by a GEIIS PACS (issues [113](https://github.com/rordenlab/dcm2niix/issues/113), [250](https://github.com/rordenlab/dcm2niix/issues/250)). In general, I would discourage use of Icon images in DICOM, they create larger files and bulk up an already complicated format.

**Comment by dagra** [comment] 2020-07-14 17:23
I checked the latest dev branch and it resolves the problem! Thanks!

Regarding the unintended consequences, do you mean that eventually this commit may be reverted and/or not be included in the releases at all?

**Comment by neurolabusc** [comment] 2020-07-14 17:43
The GEIIS systems sold for about a decade would insert an icon into each DICOM image they touched. Some of these systems are still in service today. The implementation was in violation of the DICOM standard, and caused [unexpected behavior](https://forum.dcmtk.org/viewtopic.php?t=2016). It seems that many tools (including anonymization scripts) had problems with these icons and mangled the DICOM header further. Therefore, the challenge is that these GEIIS images are very common, but it seems that different users have files that are mangled in different ways. The current dcm2niix code has several kludges designed to handle these variations. While the latest commit addresses your issue, it may disrupt the delicate balance of the other kludges. If this new solution fails with other images, we will have to revisit this issue. Since you sent me a de-identified exemplar, with your permission I will keep a copy of your image long term, to ensure that future attempts to handle GEIIS images does not impair conversion of your images (where the icon format looks valid).

**Comment by dagra** [comment] 2020-07-15 10:10
OK. As long as the image is not public, it's ok with me.

Thank you very much!

**Closed** 2020-07-15 10:47 UTC
