### ISSUE TITLE
Estimated Gantry Tilt -nan(ind), but Gantry Tilt field is 0

### ISSUE THREAD

**Issue by BenyAlbatross** [rordenlab/dcm2niix#782] opened 2024-02-01 12:56 UTC
When converting a CT scan to Nifti, there is no output nifti file. There seems to be a mismatch between the estimated gantry tilt and the gantry tilt in the metadat. The last debug line that is output is
`Gantry Tilt based on 0018,1120 0, estimated from slice vector -nan(ind)
`

**Version**
 dcm2niix version v1.0.20230411 Windows

**Comment by neurolabusc** [comment] 2024-02-01 15:45
@BenyAlbatross you can try out the [gantry tilt validation tests here](https://github.com/neurolabusc/dcm_qa_ct). I really can not provide any more insight without seeing an example of the data. If you are able to share the data [send a link to my institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php).

**Comment by BenyAlbatross** [comment] 2024-02-02 14:38
Unfortunately I'm unable to share the data, but I can provide the output of the validation test:

Found 57 DICOM file(s)
Gantry Tilt Parameters (see issue 253)
 Read =[0.991124 -0.130252 0.0265963]
 Phase =[0.00839617 -0.138332 -0.99035]
 CrossReadPhase =[0.132675 0.981783 -0.13601]
 Slice =[22.2893 164.94 -22.8497]
Gantry Tilt based on 0018,1120 0, estimated from slice vector nan

**Comment by neurolabusc** [comment] 2024-02-02 14:42
Understood. I am unable to replicate so I am closing. Feel free to make a pull request if you develop a method to handle your images.

**Comment by cfhammill** [comment] 2024-02-14 20:09
I have the same issue with dicoms I'm also unable to share (although if truly necessary I might be able to construct a synthetic example), but I don't think that should be necessary as the problem is pretty clear. In my example I see the output
```
Chris Rorden's dcm2niiX version v1.0.20230411  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)
Found 63 DICOM file(s)
Gantry Tilt Parameters (see issue 253)
 Read =[0.997143 -0 0.0755325]
 Phase =[0.0111937 0.988958 -0.147774]
 CrossReadPhase =[-0.0746985 0.148197 0.986133]
 Slice =[-11.5783 22.9705 152.851]
Gantry Tilt based on 0018,1120 0, estimated from slice vector nan
```

I put the CrossReadPhase and Slice vectors into python, and follow the code from https://github.com/rordenlab/dcm2niix/blob/v1.0.20230411/console/nii_dicom_batch.cpp#L2768

```
import numpy as np
slice_vector = np.array([-11.5783, 22.9705, 152.851], dtype=np.float32)
slice_vector90 = np.array([-0.0746985, 0.148197, 0.986133], dtype=np.float32)
dotX = np.dot(slice_vector, slice_vector90)
len = np.linalg.norm(slice_vector)
len90 = np.linalg.norm(slice_vector90)
cosX = dotX / (len * len90)

np.abs(1.0 - cosX) <= np.finfo(cosX.dtype).eps 
> True
```

I see that cosX is slightly above 1, but within float32 eps.  So it should fail the not same float check at https://github.com/rordenlab/dcm2niix/blob/v1.0.20230411/console/nii_dicom_batch.cpp#L2771

And `ret` should not be modified. It would then pass the same float as 0 at
https://github.com/rordenlab/dcm2niix/blob/v1.0.20230411/console/nii_dicom_batch.cpp#L2778

But since passing that check would mean the function returns early and does not produce the gantry tilt output observed above it must be that this test does not pass, which would mean `ret` gets set above, so it seems likely `cosX` is not the same float as 1 in the cpp code. And since the number already appears above 1, it seems likely it is just big enough to fail the same float test. I tested experimentally adding a small quantity to `cosX`

```
np.abs(np.float32(1) - (cosX + np.finfo(cosX.dtype).eps/2)) <= np.finfo(cosX.dtype).eps
> False
```

```
np.arccos(cosX + np.finfo(cosX.dtype).eps/2)
> nan
```

this would explain why `ret` = `nan` as shown in the output above. Why exactly the `cosX` would end up being more than float32 epsilon above 1 isn't clear to me, but adding a defensive check that `cosX` is not more than one would likely fix this problem.

https://github.com/rordenlab/dcm2niix/blob/v1.0.20230411/console/nii_dicom_batch.cpp#L2771 

```
## Current 
if (!isSameFloat(cosX, 1.0))
## Proposal
if(! (isSameFloat(cosX, 1.0) || cosX > 1.0))
```

**Comment by neurolabusc** [comment] 2024-02-14 21:44
Sorry, I can not replicate your findings with the values you provided. Perhaps this relates to the precision used for reporting these, or some other issue. The opportunity for unintended consequences is high, so I am reluctant to explore problems where I do not have access to a concrete example. Feel free to submit a pull request if you solve this.

**Closed** 2024-02-16 15:29 UTC
