### ISSUE TITLE
How to get 3D nii file?

### ISSUE THREAD

**Issue by mgcyung** [rordenlab/dcm2niix#313] opened 2019-07-21 10:56 UTC
I'm new to dicom and nii format. Thanks in advanced.

The dcm is converted to nii by command

``` shell
dcm2niix -z y -o min-worker-2-dcm min-worker-2-dcm
```

And the message says

```
Unable to determine slice thickness: please check voxel size
Warning: Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor.
 Warning: all images appear to be a single slice - please check slice/vector orientation
Convert 992 DICOM as min-worker-2-dcm/min-worker-2-dcm_Pancreas_20151124165448_1305501634 (512x512x1x992)
Warning: Check that 2D images are not mirrored.
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "min-worker-2-dcm/min-worker-2-dcm_Pancreas_20151124165448_1305501634.nii"
Conversion required 4.524280 seconds (2.968979 for core code).
```

The dimension of nii file is 512x512x1x992, however, I need
512x512x992. How to get 3 dimensions?

**Comment by neurolabusc** [comment] 2019-07-21 12:48
1.) What is the origin of your source image? I would check the providence of your data. It looks like all slices of your data report being from the same spatial location (or omit spatial location altogether). If your data is really a 3D volume, this reflects a limitation in your DICOM data and not my software. I suspect this data got mangled at some prior stage of processing (e.g. anonymization). If so, you should get a good result if you can convert the data prior to removal of required DICOM tags.

2.) You can change your NIfTI image from 4D to 3D by editing the header. There are many tools for this, but here I give instructions for [MRIcron](https://www.nitrc.org/projects/mricron). 
- Open your NIfTI image with MRIcron
- Choose the Windows/Information menu item
- Change the "K Space"/"Dim" value from "1" to "992"
- Change the "Time"/"Dim" value from "992" to "1"
- If you know the distance between slices (in mm), set this as the "KSpace"/"Spacing" value.
- Choose File/SaveHeader to save your modified image.
-Re-open the modified image.

**Comment by mgcyung** [comment] 2019-07-21 15:13
1) The source images are tiff files which are slices of a volume from
CT scanning. The meta information is missing. I used imagemagick ,
img2dcm and dcm2niix to convert them into nifti. The nifti is used as
infput of a segmentation CNN which needs 3 dimensions in the input
nifti file. There is nothing wrong with you software. It is a good
job.

2) The function to change the NIfTI image from 4D to 3D by editing the
header is exactly what I need. I tried MRIcron of v1.0.20190410 and
v1.0.20181114 on windows. However, there is no File/SaveHeader in the
menu item "File". Should I try some other versions?

**Comment by neurolabusc** [comment] 2019-07-21 17:46
Curious, I can confirm you [issue](https://github.com/neurolabusc/MRIcron/issues/12). Will be fixed in the next release. In the mean time, press Ctrl+S while the header information form is focused, and you will be able to save your header. Just overwrite your old header.

**Comment by mgcyung** [comment] 2019-07-21 23:58
Ctrl+S works as you said. Thanks.

**Closed** 2019-07-22 17:10 UTC
