### ISSUE TITLE
Newer versions not recognizing EchoTrainLength

### ISSUE THREAD

**Issue by RebeccaAHayes** [rordenlab/dcm2niix#757] opened 2023-09-22 17:16 UTC
**Describe the bug**

Our lab had been using dcm2niix v1.0.20200331 to convert dicoms for our Siemens Prisma 3d-QALAS scans into nii format. That 2020 version of the software did, and still does, extract the dicom header field “EchoTrainLength” into the .json sidecar. We recently updated to dcm2niix v1.0.20230411 via conda-forge, and EchoTrainLength is no longer included in the .json.

**To reproduce**

1. Run the command 'dcm2niix [directory name]'
2. Review .json file

[old_convertbids_qalas.json.txt](https://github.com/rordenlab/dcm2niix/files/12703068/old_convertbids_qalas.json.txt)
[new_convertbids_qalas.json.txt](https://github.com/rordenlab/dcm2niix/files/12703069/new_convertbids_qalas.json.txt)

**Expected behavior**

We expected the 20230411 version to extract EchoTrainLength similarly to the 20200331 version.

**Output log**

Chris Rorden's dcm2niiX version v1.0.20230411  GCC12.2.0 x86-64 (64-bit Linux)
Found 10 DICOM file(s)
5 images have identical time, series, acquisition and instance values. DUPLICATES REMOVED.
Convert 5 DICOM as ./_-QALAS3d_1p3mm_R2-QALAS3d_1p3mm_R2-26 (192x192x144x5)
Compress: "/programs/x86_64-linux/system/biogrids_bin/pigz" -b 960 -n -f -6 "./_-QALAS3d_1p3mm_R2-QALAS3d_1p3mm_R2-26.nii"
Conversion required 3.793750 seconds (0.190000 for core code).

**Version**

Please report the complete version string:

  v1.0.20230411  GCC12.2.0 x86-64 (64-bit Linux)
  (old version that worked was  v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux))

**Comment by neurolabusc** [comment] 2023-09-22 17:20
[duplicate of issue 717](https://github.com/rordenlab/dcm2niix/issues/717). Feel free to test the development branch:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix
```

**Closed** 2023-10-01 12:42 UTC
Labels: duplicate
