### ISSUE TITLE
Unable to extract PhaseEncodingDirection when dcm2niix converts to UIH data

### ISSUE THREAD

**Issue by XYWCQM** [rordenlab/dcm2niix#410] opened 2020-07-15 08:33 UTC
Hello:
  When I use dcm2niix to convert UIH data, there is no PhaseEncodingDirection in the json file, only PhaseEncodingAxis. I checked part of the code of dcm2niix and related issues in the past, and found that you can't get Phaseencoding polarity over there. In fact, there is relevant information in UIH dicom (Tag ID: 0065, 1058). Tag ID: 0065,1058, when equal to 1, it corresponds to the PA encoding direction, and when equal to 0, it corresponds to the AP direction encoding. Looking forward to your reply, thank you.

**Comment by neurolabusc** [comment] 2020-07-15 10:47
Can you provide a small dataset that includes this tag, either the public or emailed to me directly? The sample [UIH datasets](https://github.com/neurolabusc/dcm_qa_uih) include AP and PA acquisitions, but do not include the private tag 0065,1058. Beyond knowing the values (0 and 1) on also needs to specify the VR (IS, LO, ST, etc.). As a minimum, can you provide a dcmdump or gdcmdump for an image with this new tag?

**Comment by XYWCQM** [comment] 2020-07-16 03:16
Thank you for your reply. The attachment is sample data, please check it, thank you.
[sample_data.zip](https://github.com/rordenlab/dcm2niix/files/4929079/sample_data.zip)

**Comment by neurolabusc** [comment] 2020-07-16 11:02
@XYWCQM  this private tag is now supported with the latest commit to the development branch. Please test and close issue if you are happy with the solution. @xiangruili the provided sample data should allow you to support this with [dicm2nii](https://github.com/xiangruili/dicm2nii). The tag 0065,1058 VR is [IS](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html), analogous to the Siemens 0021,111C.

```
A->P
(0065,1058) IS [0]                                      #   2, 1 Unknown Tag & Data
P->A
(0065,1058) IS [1]                                      #   2, 1 Unknown Tag & Data
```

**Comment by xiangruili** [comment] 2020-07-16 21:07
@neurolabusc Thank you for alerting me. For Siemens, A>>P gives PhaseEncodingDirectionPositive=1. If I understand correctly, this UIH tag is opposite to Siemens PhaseEncodingDirectionPositive . 

@XYWCQM Do you have any idea what this tag is called by UIH? They provided meaning for their private tags (like [this](https://github.com/rordenlab/dcm2niix/tree/master/UIH)), but we don't have the meaning for those they added later.
The meaning of this tag will be helpful, so we can deal with other phase direction (like RL, LR) correctly.

I hope they don't store NIfTI direction in DICOM file (like GE).

**Comment by xiangruili** [comment] 2020-07-16 21:33
I am guessing (0065,1058) of 1 means to inverse the PE direction shown in
(0065,1005) SH PEDirectionDisplayed   # A->P
This seems similar to the CMRR MB sequence, where a parameter indicates reversed RO/PE direction.

Anyway, information from the manufacturer can avoid these kind of guess work.

**Comment by XYWCQM** [comment] 2020-07-17 10:04
**@xiangruili** Your guess is correct.  (0065,1058) of 1 means to inverse the PE direction shown in (0065,1005) SH PEDirectionDisplayed # A->P, R->L is the same rule. 
**@neurolabusc** Do you need to make changes accordingly? Thank you.

**Comment by neurolabusc** [comment] 2020-07-17 10:33
@XYWCQM would it be convenient for you to provide a pair of images with L->R and R->L phase encoding? That would provide @xiangruili a concrete example for this behavior. Thanks again for the sample dataset.

**Comment by xiangruili** [comment] 2020-07-17 15:30
@XYWCQM Thanks for the dataset and confirming the tag meaning. 
I just updated [dicm2nii package](https://github.com/xiangruili/dicm2nii).
As @neurolabusc suggested, a pair of R->L images would be nice to verify the result.

**Comment by XYWCQM** [comment] 2020-07-20 05:27
**@xiangruili @neurolabusc** Thank you for your reply. The attachment is sample data, please check it, thank you.
[data(RL).zip](https://github.com/rordenlab/dcm2niix/files/4945643/data.RL.zip)
**@xiangruili** Does dcm2nii support UIH mosaic images?

**Comment by xiangruili** [comment] 2020-07-20 15:12
@XYWCQM Both conversion tools support UIH mosaic images. 
The RL dataset result looks good to me with my latest update for dicm2nii.m. 
Thanks.

**Comment by XYWCQM** [comment] 2020-07-21 01:17
**@xiangruili** Thank you for your reply. Good luck.
**@neurolabusc**  Is there any problem with RL dataset test? Thanks.

**Comment by neurolabusc** [comment] 2020-07-21 11:10
All good. I am closing this issue, this feature is supported by the current development branch and will be part of the next stable release.

**Closed by neurolabusc** 2020-07-21 11:10 UTC

**Comment by XYWCQM** [comment] 2020-07-23 04:05
**@neurolabusc** When I tested your latest code, I found that when dcm2niix and dcm2nii converted UIH data, the extracted PhaseEncodingDirection (RL) directions were inconsistent. Is the direction defined by you inconsistent?

**Comment by XYWCQM** [comment] 2020-07-23 04:05
Hi:
   When i tested your latest code, i found that when dcm2niix and dcm2nii converted UIH data, the extracted PhaseEncodingDirection(RL) directions were inconsistent. Is the direction defined by you inconsistent? Thank you.
















At 2020-07-21 19:10:16, "Chris Rorden" <notifications@github.com> wrote:

All good. I am closing this issue, this feature is supported by the current development branch and will be part of the next stable release.

**Comment by xiangruili** [comment] 2020-07-23 12:21
@XYWCQM When you compare the phase direction from dicm2nii.m and dcm2niix, are you using the same storage method, i.e. either both left-handed storage or both right-handed storage? The stored phase direction is in image reference, so if the handedness is opposite, the direction is expected to be opposite.

**Comment by neurolabusc** [comment] 2020-07-23 12:48
@XYWCQM and @xiangruili, I must recant my comments [here](https://github.com/rordenlab/dcm2niix/commit/1ed8368571e55dbf809f8c3574542f75e38c6d91#commitcomment-40835531). At the moment, dcm2niix and dicm2nii do describe different phase encoding directions. The issue is the ambiguity of which image is the L>R phase encoding and which is the R>L phase encoding. I assumed the applied polarity from the ProtocolName (0018,1030). @xiangruili did you assume the polarity based on the SeriesDescription (0008,103e)  spatial distortion observed in the image? We really need to do the latter to resolve this. The Series Description and ProtocolName conflict with each other regarding the spatial distortion:

Series 1001 reports:
(0008,103e) LO [epi_bold_64_RL_SaveBySlc]               #  24, 1 SeriesDescription
(0018,1030) LO [epi_bold_64_LR]                         #  14, 1 ProtocolName

Series 901 reports
(0008,103e) LO [epi_bold_64_LR_SaveBySlc]               #  24, 1 SeriesDescription
(0018,1030) LO [epi_bold_64_RL]                         #  14, 1 ProtocolName

**Comment by XYWCQM** [comment] 2020-07-23 14:53
I will check the (0008,103e) and (0018,1030) value, thank you.


| |
Yao-Wen Xing
邮箱：18202832726@163.com
|

Signature is customized by Netease Mail Master

On 07/23/2020 20:48, Chris Rorden wrote:

@XYWCQM and @xiangruili, I must recant my comments here. At the moment, dcm2niix and dicm2nii do describe different phase encoding directions. The issue is the ambiguity of which image is the L>R phase encoding and which is the R>L phase encoding. I assumed the applied polarity from the ProtocolName (0018,1030). @xiangruili did you assume the polarity based on the SeriesDescription (0008,103e) spatial distortion observed in the image? We really need to do the latter to resolve this. The Series Description and ProtocolName conflict with each other regarding the spatial distortion:

Series 1001 reports:
(0008,103e) LO [epi_bold_64_RL_SaveBySlc] # 24, 1 SeriesDescription
(0018,1030) LO [epi_bold_64_LR] # 14, 1 ProtocolName

Series 901 reports
(0008,103e) LO [epi_bold_64_LR_SaveBySlc] # 24, 1 SeriesDescription
(0018,1030) LO [epi_bold_64_RL] # 14, 1 ProtocolName

**Comment by xiangruili** [comment] 2020-07-26 16:28
We should rely on the image rather than the label in either description or protocol name.
The PE direction is very easy to go wrong. I thought I was done with it, but I am not confident though.
Following is the list of all 4 series. The dicm2nii.m output for x/-x direction is based on left-hand storage. 
@neurolabusc  Can you verify the PE direction from my eyeball result (last column) is correct? 
```
Series Description              ProtocolName   Displayed Flipped dicm2nii Eyeball
     7 epi_dti_b500_SaveBySlc   epi_dti_b500   A->P           1  y        P->A 
    13 epi_dti_AP_SaveBySlc     epi_dti_AP     A->P           0 -y        A->P 
   901 epi_bold_64_LR_SaveBySlc epi_bold_64_RL R->L           1 -x        L->R
  1001 epi_bold_64_RL_SaveBySlc epi_bold_64_LR R->L           0  x        R->L
```

**Comment by XYWCQM** [comment] 2020-07-27 01:57
**@neurolabusc @xiangruili** I re-uploaded a set of test data, please test it, thank you.
[dataset_new.zip](https://github.com/rordenlab/dcm2niix/files/4979478/dataset_new.zip)

**Comment by neurolabusc** [comment] 2020-07-27 13:35
@xiangruili do you have any thoughts on this? I tried looking at the [L>R Siemens data](https://github.com/neurolabusc/dcm_qa/tree/master/In/TotalReadoutTime/PF_PAT_POS_PFOV_PEres_INTERP_test2) with L->R shown in red and R->L shown in green. To my eyes, the nomenclature appears reversed. The UIH data was acquired with x2 ParallelReductionFactorInPlane, which minimizes effects. For virtually all cases, what is important is encoding that the polarity is different, so perhaps this discussion is largely academic. Are you confident regarding which of the new images is `i-` and which is `i`?

<img width="720" alt="Screen Shot 2020-07-27 at 8 43 09 AM" src="https://user-images.githubusercontent.com/8930807/88547335-93134800-cfeb-11ea-8daa-70e19f7b33e6.png">

**Comment by xiangruili** [comment] 2020-07-27 22:27
I use the image "stretch" direction to tell the phase encoding direction. For the images above in the left column, the red one is stretched to left, so I think it is R->L. This is opposite to what is expected as you pointed out. Something may not be right.

I collected [several Siemens images with different PE direction](http://ccbbiinfo.asc.ohio-state.edu/tmp/prisma_PE_dicom.zip), including a fieldmap and scout scan. My quick check indicates the "stretch" eyeballing is fine. But I had thought I was correct, wrong, correct .... It is too confusing.   

The right column above shows the UIH images, right? It seems the "new data" is the same as the previous one, but with consistent Description and Protocol Name. The red image stretches to left at the bottom of the coronal view, so I think its PE is R->L (consistent with their label), corresponding to -x in NIfTI, but will be i+ with left-handed storage.

**Comment by XYWCQM** [comment] 2020-07-30 02:53
**@neurolabusc @xiangruili** Is there any progress on RL PhaseEncondingDirection or do I need any support? Thank you.

**Comment by xiangruili** [comment] 2020-07-30 16:28
@XYWCQM We are trying to figure out the very confusing PE direction. This is a general issue, not specific to UIH images. So far your provided images should be good enough.

**Comment by neurolabusc** [comment] 2020-08-04 17:05
@XYWCQM with the existing datasets, it remains unclear whether we are describing phase encoding polarity in the same way as Siemens. I do not think this has any real practical implications, as in practice we acquire a pair of polarity opposed images assuming they show distortion of the same magnitude but opposite direction. If you wish, I am happy to close this and simply clone the output of dicm2nii (as it removes a conditional). However, for a thorough resolution, I would request you acquire another dataset, similar to dataset_new.zip but with the following changes:
 1. Turn off in-plane acceleration (SENSE/GRAPPA). This will increase the spatial distortion, magnifying the impact of phase encoding polarity.
 2. Acquire data with a human head with its more complicated susceptibility issues and more complicated appearance.

While you are acquiring additional scans, as a feature request, would it be possible for you to acquire a set of phase maps and a brief fMRI run. The idea would be to simulate data as would be acquired by someone using FSL's [FUGUE](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide) or SPM's [FieldMap Toolbox](https://www.mccauslandcenter.sc.edu/crnl/tools/fieldmap). These are dual-echo gradient echo images acquired with identical shim/FOV/alignment/etc as EPI data (e.g. fMRI). This would allow UIH users to [use these tools to undistorted their fMRI/resting state data](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE/Guide#Non-SIEMENS_data).

This is purely optional, I appreciate all your time.

**Comment by XYWCQM** [comment] 2020-08-06 02:40
**@neurolabusc** Thank you for your reply. I will collect new data and upload it as soon as possible. Thank you.

**Comment by XYWCQM** [comment] 2020-09-16 08:29
@neurolabusc Sorry, it took so long to upload data. I re-uploaded a set of test data, please test it, thank you.
@xiangruili Do you need to test again?
[test_data_2.zip](https://github.com/rordenlab/dcm2niix/files/5230857/test_data_2.zip)
